# Generated by Django 5.2.4 on 2025-07-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='contact_avatars/', verbose_name='Avatar')),
                ('additional_attributes', models.JSONField(blank=True, default=dict, verbose_name='Atributos Adicionais')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('resolved', 'Resolvida'), ('pending', 'Pendente'), ('snoozed', 'Adiada')], default='open', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Prioridade')),
                ('additional_attributes', models.JSONField(blank=True, default=dict, verbose_name='Atributos Adicionais')),
                ('last_activity_at', models.DateTimeField(auto_now=True, verbose_name='Última Atividade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('channel_type', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('webchat', 'Chat Web')], max_length=20, verbose_name='Tipo de Canal')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Configurações específicas do canal', verbose_name='Configurações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caixa de Entrada',
                'verbose_name_plural': 'Caixas de Entrada',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('incoming', 'Recebida'), ('outgoing', 'Enviada'), ('activity', 'Atividade'), ('template', 'Template')], default='incoming', max_length=20, verbose_name='Tipo de Mensagem')),
                ('content_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('file', 'Arquivo'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('location', 'Localização'), ('contact', 'Contato')], default='text', max_length=20, verbose_name='Tipo de Conteúdo')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Anexos')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('external_source_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Fonte Externa')),
                ('is_private', models.BooleanField(default=False, verbose_name='Privada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
            },
        ),
    ]
