# Generated by Django 5.2.4 on 2025-09-15 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0013_csatfeedback_csatrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='conversations.team', verbose_name='Equipe'),
        ),
    ]
