# Generated by Django 5.2.4 on 2025-12-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0016_add_contact_block_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='closing_requested_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que o encerramento foi solicitado (para janela de tolerância)', null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('open', 'Aberta'), ('closed', 'Fechada'), ('pending', 'Pendente'), ('closing', 'Encerrando')], default='open', max_length=20),
        ),
    ]
