# Generated by Django 6.0.2 on 2026-04-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0019_add_last_user_message_at'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM pg_indexes
                            WHERE schemaname = ANY (current_schemas(false))
                              AND indexname = 'message_rea_message_emoji_idx'
                        ) THEN
                            ALTER INDEX message_rea_message_emoji_idx
                            RENAME TO message_rea_message_7f9ef3_idx;
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM pg_indexes
                            WHERE schemaname = ANY (current_schemas(false))
                              AND indexname = 'message_rea_message_7f9ef3_idx'
                        ) THEN
                            ALTER INDEX message_rea_message_7f9ef3_idx
                            RENAME TO message_rea_message_emoji_idx;
                        END IF;
                    END
                    $$;
                    """,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='messagereaction',
                    new_name='message_rea_message_7f9ef3_idx',
                    old_name='message_rea_message_emoji_idx',
                ),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='waiting_for_agent',
            field=models.BooleanField(default=False, help_text='Se True, a conversa aparecerá nas filas dos atendentes humanos. Se False, está sob controle do chatbot e oculta.'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('open', 'Aberta'), ('closed', 'Fechada'), ('pending', 'Pendente'), ('snoozed', 'Com IA'), ('closing', 'Encerrando')], default='open', max_length=20),
        ),
    ]
