# Generated by Django 5.2.4 on 2025-07-16 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_label_unique_together_label_provedor_and_more'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailintegration',
            name='company',
        ),
        migrations.RemoveField(
            model_name='telegramintegration',
            name='company',
        ),
        migrations.RemoveField(
            model_name='webchatintegration',
            name='company',
        ),
        migrations.RemoveField(
            model_name='whatsappintegration',
            name='company',
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='provedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_integrations', to='core.provedor', verbose_name='Provedor'),
        ),
        migrations.AddField(
            model_name='telegramintegration',
            name='provedor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_integration', to='core.provedor', verbose_name='Provedor'),
        ),
        migrations.AddField(
            model_name='webchatintegration',
            name='provedor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webchat_integration', to='core.provedor', verbose_name='Provedor'),
        ),
        migrations.AddField(
            model_name='whatsappintegration',
            name='provedor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_integration', to='core.provedor', verbose_name='Provedor'),
        ),
    ]
