# Generated by Django 5.2.4 on 2025-07-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_remove_emailintegration_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappintegration',
            name='instance_name',
            field=models.CharField(blank=True, help_text='Nome da instância no Evolution API', max_length=100, null=True, verbose_name='Nome da Instância'),
        ),
    ]
