# Generated by Django 5.2.4 on 2025-07-16 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_initial'),
        ('core', '0014_alter_label_unique_together_label_provedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='company',
        ),
        migrations.RemoveField(
            model_name='team',
            name='company',
        ),
        migrations.AddField(
            model_name='contact',
            name='provedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.provedor', verbose_name='Provedor'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='provedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inboxes', to='core.provedor', verbose_name='Provedor'),
        ),
        migrations.AddField(
            model_name='team',
            name='provedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.provedor', verbose_name='Provedor'),
        ),
    ]
