# Generated by Django 5.2.4 on 2025-07-18 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_remove_contact_company_remove_inbox_company_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        # Criar novos modelos
        migrations.CreateModel(
            name='RecoverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('delay_minutes', models.IntegerField(default=30, help_text='Delay em minutos antes de tentar recuperar')),
                ('max_attempts', models.IntegerField(default=3, help_text='Número máximo de tentativas')),
                ('auto_discount', models.BooleanField(default=False, help_text='Aplicar desconto automático')),
                ('discount_percentage', models.IntegerField(default=10, help_text='Percentual de desconto')),
                ('keywords', models.JSONField(default=list, help_text='Palavras-chave para identificar interesse em planos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_settings', to='core.provedor')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('recovered', 'Recuperada'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('message_sent', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('response_received_at', models.DateTimeField(blank=True, null=True)),
                ('potential_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_attributes', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_attempts', to='conversations.conversation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recoveryattempt',
            constraint=models.UniqueConstraint(fields=('conversation', 'attempt_number'), name='unique_conversation_attempt'),
        ),
    ]
