# Generated by Django 5.2.4 on 2025-07-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_alter_contact_options_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='avatar',
            field=models.URLField(blank=True, help_text='URL da foto do perfil do WhatsApp', null=True),
        ),
    ]
