# Generated by Django 5.2.4 on 2025-08-30 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0012_message_file_name_message_file_size_message_file_url_and_more'),
        ('core', '0038_provedor_documentos_necessarios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSATFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji_rating', models.CharField(choices=[('😡', 'Muito insatisfeito - 1'), ('😕', 'Insatisfeito - 2'), ('😐', 'Neutro - 3'), ('🙂', 'Satisfeito - 4'), ('🤩', 'Muito satisfeito - 5')], max_length=10)),
                ('rating_value', models.IntegerField()),
                ('channel_type', models.CharField(max_length=20)),
                ('feedback_sent_at', models.DateTimeField(auto_now_add=True)),
                ('conversation_ended_at', models.DateTimeField()),
                ('response_time_minutes', models.IntegerField()),
                ('original_message', models.TextField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csat_feedbacks', to='conversations.contact')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csat_feedbacks', to='conversations.conversation')),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csat_feedbacks', to='core.provedor')),
            ],
            options={
                'db_table': 'csat_feedbacks',
                'ordering': ['-feedback_sent_at'],
            },
        ),
        migrations.CreateModel(
            name='CSATRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('responded', 'Respondido'), ('expired', 'Expirado')], default='pending', max_length=20)),
                ('conversation_ended_at', models.DateTimeField()),
                ('scheduled_send_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('channel_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csat_requests', to='conversations.contact')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csat_requests', to='conversations.conversation')),
                ('csat_feedback', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='conversations.csatfeedback')),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csat_requests', to='core.provedor')),
            ],
            options={
                'db_table': 'csat_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='csatfeedback',
            index=models.Index(fields=['provedor', 'feedback_sent_at'], name='csat_feedba_provedo_ede2d4_idx'),
        ),
        migrations.AddIndex(
            model_name='csatfeedback',
            index=models.Index(fields=['provedor', 'rating_value'], name='csat_feedba_provedo_b3934f_idx'),
        ),
        migrations.AddIndex(
            model_name='csatfeedback',
            index=models.Index(fields=['channel_type', 'provedor'], name='csat_feedba_channel_19a786_idx'),
        ),
        migrations.AddIndex(
            model_name='csatrequest',
            index=models.Index(fields=['provedor', 'status'], name='csat_reques_provedo_2ac93b_idx'),
        ),
        migrations.AddIndex(
            model_name='csatrequest',
            index=models.Index(fields=['scheduled_send_at', 'status'], name='csat_reques_schedul_91da24_idx'),
        ),
    ]
