# Generated by Django 5.2.4 on 2025-11-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0015_merge_20250915_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bloqueado_atender',
            field=models.BooleanField(default=False, help_text='Se True, a IA não responderá mensagens deste contato', verbose_name='Bloqueado para Atendimento'),
        ),
        migrations.AddField(
            model_name='contact',
            name='bloqueado_disparos',
            field=models.BooleanField(default=False, help_text='Se True, não será possível enviar disparos para este contato', verbose_name='Bloqueado para Disparos'),
        ),
    ]
