import React, { createContext, useContext, useState, useEffect } from 'react';
import axios from 'axios';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    // Retornar valores padrão ao invés de lançar erro
    // Isso evita quebrar componentes que são renderizados antes do provider
    console.warn('useLanguage está sendo usado fora do LanguageProvider. Usando valores padrão.');
    return {
      language: 'pt',
      changeLanguage: () => { },
      t: (key) => key
    };
  }
  return context;
};

// Traduções
const translations = {
  pt: {
    // Navegação
    'dashboard': 'Dashboard',
    'atendimento': 'Atendimento',
    'conversas': 'Conversas',
    'contatos': 'Contatos',
    'usuarios': 'Usuários',
    'equipes': 'Equipes',
    'auditoria': 'Auditoria',
    'csat': 'CSAT',
    'horario': 'Horário',
    'integracoes': 'Integrações',
    'dados_provedor': 'Dados do Provedor',
    'recuperador': 'Recuperador de conversas (session)',
    'perfil': 'Perfil',
    'chatbot_builder': 'Chatbot',
    'planos': 'Planos',

    // Perfil
    'informacoes_pessoais': 'Informações Pessoais',
    'nome_completo': 'Nome Completo',
    'email': 'E-mail',
    'telefone': 'Telefone',
    'idioma_sistema': 'Idioma do Sistema',
    'salvar': 'Salvar',
    'salvando': 'Salvando...',
    'perfil_atualizado': 'Perfil atualizado com sucesso!',
    'erro_atualizar': 'Erro ao atualizar perfil. Tente novamente.',

    // Notificações
    'notificacoes': 'Notificações',
    'preferencias_notificacao': 'Preferências de Notificação',
    'notificacoes_sonoras': 'Notificações Sonoras',
    'som_novas_mensagens': 'Som para novas mensagens',
    'som_novas_conversas': 'Som para novas conversas',
    'reproduzir': 'Reproduzir',

    // Segurança
    'seguranca': 'Segurança',
    'configuracoes_seguranca': 'Configurações de Segurança',
    'autenticacao_dois_fatores': 'Autenticação de Dois Fatores',
    'adicionar_camada_seguranca': 'Adicione uma camada extra de segurança à sua conta',
    'redefinir_senha': 'Redefinir Senha',
    'alterar_senha': 'Altere sua senha de acesso ao sistema',
    'alterar': 'Alterar',
    'alterando': 'Alterando...',
    'timeout_sessao': 'Timeout da Sessão (minutos)',

    // Atribuição
    'atribuicao': 'Atribuição',
    'mensagem_atribuicao': 'Mensagem de Atribuição',
    'mensagem_atribuicao_desc': 'Esta mensagem será enviada automaticamente ao cliente quando você atribuir o atendimento a si mesmo.',
    'digite_mensagem_atribuicao': 'Digite sua mensagem de atribuição aqui...',

    // Ações gerais
    'sair': 'Sair',
    'changelog': 'Changelog',
    'alternar_tema': 'Alternar tema',
    'abrir_menu': 'Abrir menu',
    'pesquisar': 'Pesquisar',
    'dashboard_superadmin': 'Dashboard Superadmin',
    'conversations': 'Atendimento',
    'contacts': 'Contatos',
    'users': 'Usuários',
    'teams': 'Equipes',
    'audit': 'Auditoria',
    'recovery': 'Recuperador de conversas',
    'session': 'session',

    // Integrações
    'canais_configurados': 'Canais Configurados',
    'adicionar_canal': 'Adicionar Canal',
    'nenhum_canal_configurado': 'Nenhum canal configurado.',
    'carregando_canais': 'Carregando canais...',
    'erro_carregar_canais': 'Erro ao carregar canais',
    'conectado': 'Conectado',
    'desconectado': 'Desconectado',
    'conectar': 'Conectar',
    'desconectar': 'Desconectar',
    'deletar_instancia': 'Deletar Instância',
    'disponivel': 'Disponível',
    'cancelar': 'Cancelar',
    'fechar': 'Fechar',
    'nome_instancia': 'Nome da Instância',
    'adicionando': 'Adicionando...',
    'adicionar_canal_btn': 'Adicionar Canal',
    'nome_canal': 'Nome do Canal',
    'email_opcional': 'E-mail (opcional)',
    'url_opcional': 'URL (opcional)',
    'configuracoes_sgp': 'Configurações do SGP',
    'url_sgp': 'URL do SGP',
    'token_sgp': 'Token do SGP',
    'app_sgp': 'App do SGP',
    'salvar_configuracoes_sgp': 'Salvar Configurações do SGP',
    'dados_sgp_salvos': 'Dados do SGP salvos com sucesso!',
    'erro_salvar_sgp': 'Erro ao salvar dados do SGP!',
    'configuracoes_whatsapp': 'Configurações do WhatsApp',
    'url_instancia': 'URL da Instância',
    'token_instancia': 'Token da Instância',
    'salvar_configuracoes_whatsapp': 'Salvar Configurações do WhatsApp',
    'dados_whatsapp_salvos': 'Dados do WhatsApp salvos com sucesso!',
    'erro_salvar_whatsapp': 'Erro ao salvar dados do WhatsApp!',
    'gerando_qr_code': 'Gerando QR Code...',
    'escanear_qr_code': 'Escaneie o QR Code no WhatsApp',
    'como_deseja_conectar': 'Como deseja conectar?',
    'codigo_pareamento': 'Código de Pareamento',
    'digite_numero_telefone': 'Digite o número de telefone (com DDD)',
    'enviando': 'Enviando...',
    'obter_codigo_pareamento': 'Obter Código de Pareamento',
    'digite_codigo_whatsapp': 'Digite este código no WhatsApp:',
    'configuracoes_aparelhos_conectados': 'Clique nos três → Dispositivos conectados → Conectar dispositivo',
    'sucesso': 'Sucesso!',
    'canal_adicionado_sucesso': 'O canal foi adicionado com sucesso!',
    'whatsapp_ja_conectado': 'WhatsApp já conectado!',
    'erro_gerar_qr_code': 'Erro ao gerar QR Code',
    'erro_criar_instancia': 'Erro ao criar instância',
    'erro_adicionar_canal': 'Erro ao adicionar canal',
    'erro_excluir_canal': 'Erro ao excluir canal',
    'canal_deletado_sucesso': 'Canal deletado com sucesso!',
    'erro_deletar_canal': 'Erro ao deletar canal',
    'whatsapp_session_desconectado': 'Sessão WhatsApp desconectada com sucesso!',
    'erro_desconectar_session': 'Erro ao desconectar WhatsApp',
    'whatsapp_desconectado': 'WhatsApp desconectado com sucesso!',
    'erro_desconectar_whatsapp': 'Erro ao desconectar WhatsApp',
    'detalhes_canal': 'Detalhes do Canal',
    'antes_conectar_whatsapp': 'Antes de conectar seu WhatsApp:',
    'evitar_bloqueios': 'Para evitar bloqueios, garanta que seu número esteja aquecido!',
    'comece_mensagens_manuais': 'Comece com mensagens manuais e interações reais.',
    'dica': 'Dica:',
    'use_whatsapp_organico': 'Use o WhatsApp de forma orgânica no início. Isso cria confiança e evita que seu número seja sinalizado.',
    'digite_codigo_ou_escaneie': 'Digite o código ou escaneie o QR Code no WhatsApp',
    'usuario_nao_autenticado': 'Usuário não autenticado',
    'gestor_chatbot': 'Gestor de Chatbots',
    'criar_novo_fluxo': 'Criar Novo Fluxo',
    'buscar_fluxos': 'Buscar fluxos pelo nome...',
    'blocos_no_fluxo': 'blocos no fluxo',
    'atualizado_em': 'Atualizado em',
    'abrir_no_editor': 'Abrir no Editor',
    'novo_fluxo': 'Novo Fluxo',
    'nome_do_fluxo': 'Nome do Fluxo',
    'criar_e_editar': 'Criar e Editar',
    'fluxo_principal': 'Fluxo Principal',
    'nenhum_fluxo_encontrado': 'Nenhum fluxo encontrado',
    'editar_fluxo': 'Editar Fluxo',
    'editar': 'Editar',
    'deletar': 'Deletar',
  },
  en: {
    // Navigation
    'dashboard': 'Dashboard',
    'atendimento': 'Service',
    'conversas': 'Conversations',
    'contatos': 'Contacts',
    'usuarios': 'Users',
    'equipes': 'Teams',
    'auditoria': 'Audit',
    'csat': 'CSAT',
    'horario': 'Schedule',
    'integracoes': 'Integrations',
    'dados_provedor': 'Provider Data',
    'recuperador': 'Conversation Recovery (session)',
    'perfil': 'Profile',

    // Profile
    'informacoes_pessoais': 'Personal Information',
    'nome_completo': 'Full Name',
    'email': 'E-mail',
    'telefone': 'Phone',
    'idioma_sistema': 'System Language',
    'salvar': 'Save',
    'salvando': 'Saving...',
    'perfil_atualizado': 'Profile updated successfully!',
    'erro_atualizar': 'Error updating profile. Please try again.',

    // Notifications
    'notificacoes': 'Notifications',
    'preferencias_notificacao': 'Notification Preferences',
    'notificacoes_sonoras': 'Sound Notifications',
    'som_novas_mensagens': 'Sound for new messages',
    'som_novas_conversas': 'Sound for new conversations',
    'reproduzir': 'Play',

    // Security
    'seguranca': 'Security',
    'configuracoes_seguranca': 'Security Settings',
    'autenticacao_dois_fatores': 'Two-Factor Authentication',
    'adicionar_camada_seguranca': 'Add an extra layer of security to your account',
    'redefinir_senha': 'Reset Password',
    'alterar_senha': 'Change your system access password',
    'alterar': 'Change',
    'alterando': 'Changing...',
    'timeout_sessao': 'Session Timeout (minutes)',

    // General actions
    'sair': 'Logout',
    'changelog': 'Changelog',
    'alternar_tema': 'Toggle theme',
    'abrir_menu': 'Open menu',
    'pesquisar': 'Search',
    'dashboard_superadmin': 'Superadmin Dashboard',
    'conversations': 'Service',
    'contacts': 'Contacts',
    'users': 'Users',
    'teams': 'Teams',
    'audit': 'Audit',
    'recovery': 'Conversation Recovery',
    'session': 'session',
    'chatbot_builder': 'Chatbot',
    'planos': 'Plans',
    'gestor_chatbot': 'Chatbot Manager',
    'criar_novo_fluxo': 'Create New Flow',
    'buscar_fluxos': 'Search flows by name...',
    'blocos_no_fluxo': 'blocks in flow',
    'atualizado_em': 'Updated at',
    'abrir_no_editor': 'Open in Editor',
    'novo_fluxo': 'New Flow',
    'nome_do_fluxo': 'Flow Name',
    'criar_e_editar': 'Create and Edit',
    'fluxo_principal': 'Main Flow',
    'nenhum_fluxo_encontrado': 'No flows found',
    'editar_fluxo': 'Edit Flow',
    'editar': 'Edit',
    'deletar': 'Delete',
  },
  es: {
    // Navegación
    'dashboard': 'Dashboard',
    'atendimento': 'Atención',
    'conversas': 'Conversaciones',
    'contatos': 'Contactos',
    'usuarios': 'Usuarios',
    'equipes': 'Equipos',
    'auditoria': 'Auditoría',
    'csat': 'CSAT',
    'horario': 'Horario',
    'integracoes': 'Integraciones',
    'dados_provedor': 'Datos del Proveedor',
    'recuperador': 'Recuperador de conversaciones (session)',
    'perfil': 'Perfil',

    // Perfil
    'informacoes_pessoais': 'Información Personal',
    'nome_completo': 'Nombre Completo',
    'email': 'Correo Electrónico',
    'telefone': 'Teléfono',
    'idioma_sistema': 'Idioma del Sistema',
    'salvar': 'Guardar',
    'salvando': 'Guardando...',
    'perfil_atualizado': '¡Perfil actualizado con éxito!',
    'erro_atualizar': 'Error al actualizar el perfil. Intente nuevamente.',

    // Notificaciones
    'notificacoes': 'Notificaciones',
    'preferencias_notificacao': 'Preferencias de Notificación',
    'notificacoes_sonoras': 'Notificaciones de Sonido',
    'som_novas_mensagens': 'Sonido para nuevos mensajes',
    'som_novas_conversas': 'Sonido para nuevas conversaciones',
    'reproduzir': 'Reproducir',

    // Seguridad
    'seguranca': 'Seguridad',
    'configuracoes_seguranca': 'Configuraciones de Seguridad',
    'autenticacao_dois_fatores': 'Autenticación de Dos Factores',
    'adicionar_camada_seguranca': 'Agregue una capa adicional de seguridad a su cuenta',
    'redefinir_senha': 'Restablecer Contraseña',
    'alterar_senha': 'Cambie su contraseña de acceso al sistema',
    'alterar': 'Cambiar',
    'alterando': 'Cambiando...',
    'timeout_sessao': 'Tiempo de Espera de Sesión (minutos)',

    // Acciones generales
    'sair': 'Salir',
    'changelog': 'Changelog',
    'alternar_tema': 'Alternar tema',
    'abrir_menu': 'Abrir menú',
    'pesquisar': 'Buscar',
    'dashboard_superadmin': 'Dashboard Superadmin',
    'conversations': 'Atención',
    'contacts': 'Contactos',
    'users': 'Usuarios',
    'teams': 'Equipos',
    'audit': 'Auditoría',
    'recovery': 'Recuperador de conversaciones',
    'session': 'session',

    // Integraciones
    'canais_configurados': 'Canales Configurados',
    'adicionar_canal': 'Agregar Canal',
    'nenhum_canal_configurado': 'Ningún canal configurado.',
    'carregando_canais': 'Cargando canales...',
    'erro_carregar_canais': 'Error al cargar canales',
    'conectado': 'Conectado',
    'desconectado': 'Desconectado',
    'conectar': 'Conectar',
    'desconectar': 'Desconectar',
    'deletar_instancia': 'Eliminar Instancia',
    'disponivel': 'Disponible',
    'cancelar': 'Cancelar',
    'fechar': 'Cerrar',
    'nome_instancia': 'Nombre de la Instancia',
    'adicionando': 'Agregando...',
    'adicionar_canal_btn': 'Agregar Canal',
    'nome_canal': 'Nombre del Canal',
    'email_opcional': 'Correo Electrónico (opcional)',
    'url_opcional': 'URL (opcional)',
    'configuracoes_sgp': 'Configuraciones del SGP',
    'url_sgp': 'URL del SGP',
    'token_sgp': 'Token del SGP',
    'app_sgp': 'App del SGP',
    'salvar_configuracoes_sgp': 'Guardar Configuraciones del SGP',
    'dados_sgp_salvos': '¡Datos del SGP guardados con éxito!',
    'erro_salvar_sgp': '¡Error al guardar datos del SGP!',
    'configuracoes_whatsapp': 'Configuraciones de WhatsApp',
    'url_instancia': 'URL de la Instancia',
    'token_instancia': 'Token de la Instancia',
    'salvar_configuracoes_whatsapp': 'Guardar Configuraciones de WhatsApp',
    'dados_whatsapp_salvos': '¡Datos de WhatsApp guardados con éxito!',
    'erro_salvar_whatsapp': '¡Error al guardar datos de WhatsApp!',
    'gerando_qr_code': 'Generando Código QR...',
    'escanear_qr_code': 'Escanee el Código QR en WhatsApp',
    'como_deseja_conectar': '¿Cómo desea conectar?',
    'codigo_pareamento': 'Código de Emparejamiento',
    'digite_numero_telefone': 'Ingrese el número de teléfono (con código de área)',
    'enviando': 'Enviando...',
    'obter_codigo_pareamento': 'Obtener Código de Emparejamiento',
    'digite_codigo_whatsapp': 'Ingrese este código en WhatsApp:',
    'configuracoes_aparelhos_conectados': 'Configuración → Dispositivos vinculados → Vincular un dispositivo',
    'sucesso': '¡Éxito!',
    'canal_adicionado_sucesso': '¡Canal agregado con éxito!',
    'whatsapp_ja_conectado': '¡WhatsApp ya está conectado!',
    'erro_gerar_qr_code': 'Error al generar Código QR',
    'erro_criar_instancia': 'Error al crear instancia',
    'erro_adicionar_canal': 'Error al agregar canal',
    'erro_excluir_canal': 'Error al eliminar canal',
    'canal_deletado_sucesso': '¡Canal eliminado con éxito!',
    'erro_deletar_canal': 'Error al eliminar canal',
    'whatsapp_session_desconectado': '¡Sesión WhatsApp desconectada con éxito!',
    'erro_desconectar_session': 'Error al desconectar WhatsApp',
    'whatsapp_desconectado': '¡WhatsApp desconectado con éxito!',
    'erro_desconectar_whatsapp': 'Error al desconectar WhatsApp',
    'detalhes_canal': 'Detalles del Canal',
    'antes_conectar_whatsapp': 'Antes de conectar su WhatsApp:',
    'evitar_bloqueios': '¡Para evitar bloqueos, asegúrese de que su número esté calentado!',
    'comece_mensagens_manuais': 'Comience con mensajes manuales e interacciones reales.',
    'dica': 'Consejo:',
    'use_whatsapp_organico': 'Use WhatsApp de forma orgánica al principio. Esto genera confianza y evita que su número sea marcado.',
    'digite_codigo_ou_escaneie': 'Ingrese el código o escanee el Código QR en WhatsApp',
    'usuario_nao_autenticado': 'Usuario no autenticado',
    'chatbot_builder': 'Chatbot',
    'planos': 'Planes',
    'gestor_chatbot': 'Gestor de Chatbots',
    'criar_novo_fluxo': 'Crear Nuevo Flujo',
    'buscar_fluxos': 'Buscar flujos por nombre...',
    'blocos_no_fluxo': 'bloques en el flujo',
    'atualizado_em': 'Actualizado el',
    'abrir_no_editor': 'Abrir en el Editor',
    'novo_fluxo': 'Nuevo Flujo',
    'nome_do_fluxo': 'Nombre del Flujo',
    'criar_e_editar': 'Crear y Editar',
    'fluxo_principal': 'Flujo Principal',
    'nenhum_fluxo_encontrado': 'No se encontraron flujos',
    'editar_fluxo': 'Editar Flujo',
    'editar': 'Editar',
    'deletar': 'Eliminar',
  },
  fr: {
    // Navigation
    'dashboard': 'Tableau de bord',
    'atendimento': 'Service',
    'conversas': 'Conversations',
    'contatos': 'Contacts',
    'usuarios': 'Utilisateurs',
    'equipes': 'Équipes',
    'auditoria': 'Audit',
    'csat': 'CSAT',
    'horario': 'Horaire',
    'integracoes': 'Intégrations',
    'dados_provedor': 'Données du fournisseur',
    'recuperador': 'Récupération de conversations (session)',
    'perfil': 'Profil',

    // Profil
    'informacoes_pessoais': 'Informations personnelles',
    'nome_completo': 'Nom complet',
    'email': 'E-mail',
    'telefone': 'Téléphone',
    'idioma_sistema': 'Langue du système',
    'salvar': 'Enregistrer',
    'salvando': 'Enregistrement...',
    'perfil_atualizado': 'Profil mis à jour avec succès!',
    'erro_atualizar': 'Erreur lors de la mise à jour du profil. Veuillez réessayer.',

    // Notifications
    'notificacoes': 'Notifications',
    'preferencias_notificacao': 'Préférences de notification',
    'notificacoes_sonoras': 'Notifications sonores',
    'som_novas_mensagens': 'Son pour nouveaux messages',
    'som_novas_conversas': 'Son pour nouvelles conversations',
    'reproduzir': 'Lire',

    // Sécurité
    'seguranca': 'Sécurité',
    'configuracoes_seguranca': 'Paramètres de sécurité',
    'autenticacao_dois_fatores': 'Authentification à deux facteurs',
    'adicionar_camada_seguranca': 'Ajoutez une couche supplémentaire de sécurité à votre compte',
    'redefinir_senha': 'Réinitialiser le mot de passe',
    'alterar_senha': 'Changez votre mot de passe d\'accès au système',
    'alterar': 'Changer',
    'alterando': 'Changement...',
    'timeout_sessao': 'Délai d\'expiration de la session (minutes)',

    // Actions générales
    'sair': 'Déconnexion',
    'changelog': 'Changelog',
    'alternar_tema': 'Changer le thème',
    'abrir_menu': 'Ouvrir le menu',
    'pesquisar': 'Rechercher',
    'dashboard_superadmin': 'Tableau de bord Superadmin',
    'conversations': 'Service',
    'contacts': 'Contacts',
    'users': 'Utilisateurs',
    'teams': 'Équipes',
    'audit': 'Audit',
    'recovery': 'Récupération de conversations',
    'session': 'session',

    // Intégrations
    'canais_configurados': 'Canaux Configurés',
    'adicionar_canal': 'Ajouter un Canal',
    'nenhum_canal_configurado': 'Aucun canal configuré.',
    'carregando_canais': 'Chargement des canaux...',
    'erro_carregar_canais': 'Erreur lors du chargement des canaux',
    'conectado': 'Connecté',
    'desconectado': 'Déconnecté',
    'conectar': 'Connecter',
    'desconectar': 'Déconnecter',
    'deletar_instancia': 'Supprimer l\'Instance',
    'disponivel': 'Disponible',
    'cancelar': 'Annuler',
    'fechar': 'Fermer',
    'nome_instancia': 'Nom de l\'Instance',
    'adicionando': 'Ajout...',
    'adicionar_canal_btn': 'Ajouter un Canal',
    'nome_canal': 'Nom du Canal',
    'email_opcional': 'E-mail (optionnel)',
    'url_opcional': 'URL (optionnel)',
    'configuracoes_sgp': 'Paramètres SGP',
    'url_sgp': 'URL SGP',
    'token_sgp': 'Token SGP',
    'app_sgp': 'App SGP',
    'salvar_configuracoes_sgp': 'Enregistrer les Paramètres SGP',
    'dados_sgp_salvos': 'Données SGP enregistrées avec succès!',
    'erro_salvar_sgp': 'Erreur lors de l\'enregistrement des données SGP!',
    'configuracoes_whatsapp': 'Paramètres WhatsApp',
    'url_instancia': 'URL de l\'Instance',
    'token_instancia': 'Token de l\'Instance',
    'salvar_configuracoes_whatsapp': 'Enregistrer les Paramètres WhatsApp',
    'dados_whatsapp_salvos': 'Données WhatsApp enregistrées avec succès!',
    'erro_salvar_whatsapp': 'Erreur lors de l\'enregistrement des données WhatsApp!',
    'gerando_qr_code': 'Génération du Code QR...',
    'escanear_qr_code': 'Scannez le Code QR sur WhatsApp',
    'como_deseja_conectar': 'Comment souhaitez-vous vous connecter?',
    'codigo_pareamento': 'Code de Jumelage',
    'digite_numero_telefone': 'Entrez le numéro de téléphone (avec indicatif)',
    'enviando': 'Envoi...',
    'obter_codigo_pareamento': 'Obtenir le Code de Jumelage',
    'digite_codigo_whatsapp': 'Entrez ce code sur WhatsApp:',
    'configuracoes_aparelhos_conectados': 'Paramètres → Appareils liés → Lier un appareil',
    'sucesso': 'Succès!',
    'canal_adicionado_sucesso': 'Canal ajouté avec succès!',
    'whatsapp_ja_conectado': 'WhatsApp déjà connecté!',
    'erro_gerar_qr_code': 'Erreur lors de la génération du Code QR',
    'erro_criar_instancia': 'Erreur lors de la création de l\'instance',
    'erro_adicionar_canal': 'Erreur lors de l\'ajout du canal',
    'erro_excluir_canal': 'Erreur lors de la suppression du canal',
    'canal_deletado_sucesso': 'Canal supprimé avec succès!',
    'erro_deletar_canal': 'Erreur lors de la suppression du canal',
    'whatsapp_session_desconectado': 'Session WhatsApp déconnectée avec succès!',
    'erro_desconectar_session': 'Erreur lors de la déconnexion de WhatsApp',
    'whatsapp_desconectado': 'WhatsApp déconnecté avec succès!',
    'erro_desconectar_whatsapp': 'Erreur lors de la déconnexion de WhatsApp',
    'detalhes_canal': 'Détails du Canal',
    'antes_conectar_whatsapp': 'Avant de connecter votre WhatsApp:',
    'evitar_bloqueios': 'Pour éviter les blocages, assurez-vous que votre numéro soit réchauffé!',
    'comece_mensagens_manuais': 'Commencez par des messages manuels et des interactions réelles.',
    'dica': 'Astuce:',
    'use_whatsapp_organico': 'Utilisez WhatsApp de manière organique au début. Cela crée la confiance et évite que votre numéro soit signalé.',
    'digite_codigo_ou_escaneie': 'Entrez le code ou scannez le Code QR sur WhatsApp',
    'usuario_nao_autenticado': 'Utilisateur non authentifié',
    'chatbot_builder': 'Chatbot',
    'planos': 'Plans',
    'gestor_chatbot': 'Gestionnaire de Chatbots',
    'criar_novo_fluxo': 'Créer un Nouveau Flux',
    'buscar_fluxos': 'Rechercher des flux par nom...',
    'blocos_no_fluxo': 'blocs dans le flux',
    'atualizado_em': 'Mis à jour le',
    'abrir_no_editor': 'Ouvrir dans l\'Éditeur',
    'novo_fluxo': 'Nouveau Flux',
    'nome_do_fluxo': 'Nom du Flux',
    'criar_e_editar': 'Créer et Éditer',
    'fluxo_principal': 'Flux Principal',
    'nenhum_fluxo_encontrado': 'Aucun flux trouvé',
    'editar_fluxo': 'Modifier le Flux',
    'editar': 'Modifier',
    'deletar': 'Supprimer',
  },
  de: {
    // Navigation
    'dashboard': 'Dashboard',
    'atendimento': 'Service',
    'conversas': 'Konversationen',
    'contatos': 'Kontakte',
    'usuarios': 'Benutzer',
    'equipes': 'Teams',
    'auditoria': 'Audit',
    'csat': 'CSAT',
    'horario': 'Zeitplan',
    'integracoes': 'Integrationen',
    'dados_provedor': 'Anbieterdaten',
    'recuperador': 'Konversationswiederherstellung (session)',
    'perfil': 'Profil',

    // Profil
    'informacoes_pessoais': 'Persönliche Informationen',
    'nome_completo': 'Vollständiger Name',
    'email': 'E-Mail',
    'telefone': 'Telefon',
    'idioma_sistema': 'Systemsprache',
    'salvar': 'Speichern',
    'salvando': 'Wird gespeichert...',
    'perfil_atualizado': 'Profil erfolgreich aktualisiert!',
    'erro_atualizar': 'Fehler beim Aktualisieren des Profils. Bitte versuchen Sie es erneut.',

    // Benachrichtigungen
    'notificacoes': 'Benachrichtigungen',
    'preferencias_notificacao': 'Benachrichtigungseinstellungen',
    'notificacoes_sonoras': 'Tonbenachrichtigungen',
    'som_novas_mensagens': 'Ton für neue Nachrichten',
    'som_novas_conversas': 'Ton für neue Konversationen',
    'reproduzir': 'Abspielen',

    // Sicherheit
    'seguranca': 'Sicherheit',
    'configuracoes_seguranca': 'Sicherheitseinstellungen',
    'autenticacao_dois_fatores': 'Zwei-Faktor-Authentifizierung',
    'adicionar_camada_seguranca': 'Fügen Sie eine zusätzliche Sicherheitsebene zu Ihrem Konto hinzu',
    'redefinir_senha': 'Passwort zurücksetzen',
    'alterar_senha': 'Ändern Sie Ihr Systemzugriffspasswort',
    'alterar': 'Ändern',
    'alterando': 'Wird geändert...',
    'timeout_sessao': 'Sitzungstimeout (Minuten)',

    // Allgemeine Aktionen
    'sair': 'Abmelden',
    'changelog': 'Changelog',
    'alternar_tema': 'Thema wechseln',
    'abrir_menu': 'Menü öffnen',
    'pesquisar': 'Suchen',
    'dashboard_superadmin': 'Superadmin Dashboard',
    'conversations': 'Service',
    'contacts': 'Kontakte',
    'users': 'Benutzer',
    'teams': 'Teams',
    'audit': 'Audit',
    'recovery': 'Konversationswiederherstellung',
    'session': 'session',

    // Integrationen
    'canais_configurados': 'Konfigurierte Kanäle',
    'adicionar_canal': 'Kanal Hinzufügen',
    'nenhum_canal_configurado': 'Kein Kanal konfiguriert.',
    'carregando_canais': 'Kanäle werden geladen...',
    'erro_carregar_canais': 'Fehler beim Laden der Kanäle',
    'conectado': 'Verbunden',
    'desconectado': 'Getrennt',
    'conectar': 'Verbinden',
    'desconectar': 'Trennen',
    'deletar_instancia': 'Instanz Löschen',
    'disponivel': 'Verfügbar',
    'cancelar': 'Abbrechen',
    'fechar': 'Schließen',
    'nome_instancia': 'Instanzname',
    'adicionando': 'Hinzufügen...',
    'adicionar_canal_btn': 'Kanal Hinzufügen',
    'nome_canal': 'Kanalname',
    'email_opcional': 'E-Mail (optional)',
    'url_opcional': 'URL (optional)',
    'configuracoes_sgp': 'SGP-Einstellungen',
    'url_sgp': 'SGP-URL',
    'token_sgp': 'SGP-Token',
    'app_sgp': 'SGP-App',
    'salvar_configuracoes_sgp': 'SGP-Einstellungen Speichern',
    'dados_sgp_salvos': 'SGP-Daten erfolgreich gespeichert!',
    'erro_salvar_sgp': 'Fehler beim Speichern der SGP-Daten!',
    'configuracoes_whatsapp': 'WhatsApp-Einstellungen',
    'url_instancia': 'Instanz-URL',
    'token_instancia': 'Instanz-Token',
    'salvar_configuracoes_whatsapp': 'WhatsApp-Einstellungen Speichern',
    'dados_whatsapp_salvos': 'WhatsApp-Daten erfolgreich gespeichert!',
    'erro_salvar_whatsapp': 'Fehler beim Speichern der WhatsApp-Daten!',
    'gerando_qr_code': 'QR-Code wird generiert...',
    'escanear_qr_code': 'Scannen Sie den QR-Code auf WhatsApp',
    'como_deseja_conectar': 'Wie möchten Sie sich verbinden?',
    'codigo_pareamento': 'Paarungscode',
    'digite_numero_telefone': 'Telefonnummer eingeben (mit Vorwahl)',
    'enviando': 'Senden...',
    'obter_codigo_pareamento': 'Paarungscode Abrufen',
    'digite_codigo_whatsapp': 'Geben Sie diesen Code auf WhatsApp ein:',
    'configuracoes_aparelhos_conectados': 'Einstellungen → Verknüpfte Geräte → Gerät verknüpfen',
    'sucesso': 'Erfolg!',
    'canal_adicionado_sucesso': 'Kanal erfolgreich hinzugefügt!',
    'whatsapp_ja_conectado': 'WhatsApp bereits verbunden!',
    'erro_gerar_qr_code': 'Fehler beim Generieren des QR-Codes',
    'erro_criar_instancia': 'Fehler beim Erstellen der Instanz',
    'erro_adicionar_canal': 'Fehler beim Hinzufügen des Kanals',
    'erro_excluir_canal': 'Fehler beim Löschen des Kanals',
    'canal_deletado_sucesso': 'Kanal erfolgreich gelöscht!',
    'erro_deletar_canal': 'Fehler beim Löschen des Kanals',
    'whatsapp_session_desconectado': 'WhatsApp-Session erfolgreich getrennt!',
    'erro_desconectar_session': 'Fehler beim Trennen von WhatsApp',
    'whatsapp_desconectado': 'WhatsApp erfolgreich getrennt!',
    'erro_desconectar_whatsapp': 'Fehler beim Trennen von WhatsApp',
    'detalhes_canal': 'Kanaldetails',
    'antes_conectar_whatsapp': 'Vor dem Verbinden Ihres WhatsApp:',
    'evitar_bloqueios': 'Um Blockierungen zu vermeiden, stellen Sie sicher, dass Ihre Nummer aufgewärmt ist!',
    'comece_mensagens_manuais': 'Beginnen Sie mit manuellen Nachrichten und echten Interaktionen.',
    'dica': 'Tipp:',
    'use_whatsapp_organico': 'Verwenden Sie WhatsApp anfangs organisch. Dies schafft Vertrauen und verhindert, dass Ihre Nummer markiert wird.',
    'digite_codigo_ou_escaneie': 'Geben Sie den Code ein oder scannen Sie den QR-Code auf WhatsApp',
    'usuario_nao_autenticado': 'Benutzer nicht authentifiziert',
    'chatbot_builder': 'Chatbot',
    'planos': 'Pläne',
    'gestor_chatbot': 'Chatbot-Manager',
    'criar_novo_fluxo': 'Neuen Flow erstellen',
    'buscar_fluxos': 'Flows nach Namen suchen...',
    'blocos_no_fluxo': 'Blöcke im Flow',
    'atualizado_em': 'Aktualisiert am',
    'abrir_no_editor': 'Im Editor öffnen',
    'novo_fluxo': 'Neuer Flow',
    'nome_do_fluxo': 'Flow-Name',
    'criar_e_editar': 'Erstellen und Bearbeiten',
    'fluxo_principal': 'Hauptflow',
    'nenhum_fluxo_encontrado': 'Keine Flows gefunden',
    'editar_fluxo': 'Flow bearbeiten',
    'editar': 'Bearbeiten',
    'deletar': 'Löschen',
  },
  it: {
    // Navigazione
    'dashboard': 'Dashboard',
    'atendimento': 'Servizio',
    'conversas': 'Conversazioni',
    'contatos': 'Contatti',
    'usuarios': 'Utenti',
    'equipes': 'Squadre',
    'auditoria': 'Audit',
    'csat': 'CSAT',
    'horario': 'Orario',
    'integracoes': 'Integrazioni',
    'dados_provedor': 'Dati del fornitore',
    'recuperador': 'Recupero conversazioni (session)',
    'perfil': 'Profilo',

    // Profilo
    'informacoes_pessoais': 'Informazioni personali',
    'nome_completo': 'Nome completo',
    'email': 'E-mail',
    'telefone': 'Telefono',
    'idioma_sistema': 'Lingua del sistema',
    'salvar': 'Salva',
    'salvando': 'Salvataggio...',
    'perfil_atualizado': 'Profilo aggiornato con successo!',
    'erro_atualizar': 'Errore durante l\'aggiornamento del profilo. Riprova.',

    // Notifiche
    'notificacoes': 'Notifiche',
    'preferencias_notificacao': 'Preferenze di notifica',
    'notificacoes_sonoras': 'Notifiche sonore',
    'som_novas_mensagens': 'Suono per nuovi messaggi',
    'som_novas_conversas': 'Suono per nuove conversazioni',
    'reproduzir': 'Riproduci',

    // Sicurezza
    'seguranca': 'Sicurezza',
    'configuracoes_seguranca': 'Impostazioni di sicurezza',
    'autenticacao_dois_fatores': 'Autenticazione a due fattori',
    'adicionar_camada_seguranca': 'Aggiungi un livello extra di sicurezza al tuo account',
    'redefinir_senha': 'Reimposta password',
    'alterar_senha': 'Cambia la password di accesso al sistema',
    'alterar': 'Cambia',
    'alterando': 'Cambiamento...',
    'timeout_sessao': 'Timeout sessione (minuti)',

    // Azioni generali
    'sair': 'Esci',
    'changelog': 'Changelog',
    'alternar_tema': 'Cambia tema',
    'abrir_menu': 'Apri menu',
    'pesquisar': 'Cerca',
    'dashboard_superadmin': 'Dashboard Superadmin',
    'conversations': 'Servizio',
    'contacts': 'Contatti',
    'users': 'Utenti',
    'teams': 'Squadre',
    'audit': 'Audit',
    'recovery': 'Recupero conversazioni',
    'session': 'session',

    // Integrazioni
    'canais_configurados': 'Canali Configurati',
    'adicionar_canal': 'Aggiungi Canale',
    'nenhum_canal_configurado': 'Nessun canale configurato.',
    'carregando_canais': 'Caricamento canali...',
    'erro_carregar_canais': 'Errore nel caricamento dei canali',
    'conectado': 'Connesso',
    'desconectado': 'Disconnesso',
    'conectar': 'Connetti',
    'desconectar': 'Disconnetti',
    'deletar_instancia': 'Elimina Istanza',
    'disponivel': 'Disponibile',
    'cancelar': 'Annulla',
    'fechar': 'Chiudi',
    'nome_instancia': 'Nome Istanza',
    'adicionando': 'Aggiunta...',
    'adicionar_canal_btn': 'Aggiungi Canale',
    'nome_canal': 'Nome Canale',
    'email_opcional': 'E-mail (opzionale)',
    'url_opcional': 'URL (opzionale)',
    'configuracoes_sgp': 'Impostazioni SGP',
    'url_sgp': 'URL SGP',
    'token_sgp': 'Token SGP',
    'app_sgp': 'App SGP',
    'salvar_configuracoes_sgp': 'Salva Impostazioni SGP',
    'dados_sgp_salvos': 'Dati SGP salvati con successo!',
    'erro_salvar_sgp': 'Errore nel salvataggio dei dati SGP!',
    'configuracoes_whatsapp': 'Impostazioni WhatsApp',
    'url_instancia': 'URL Istanza',
    'token_instancia': 'Token Istanza',
    'salvar_configuracoes_whatsapp': 'Salva Impostazioni WhatsApp',
    'dados_whatsapp_salvos': 'Dati WhatsApp salvati con successo!',
    'erro_salvar_whatsapp': 'Errore nel salvataggio dei dati WhatsApp!',
    'gerando_qr_code': 'Generazione Codice QR...',
    'escanear_qr_code': 'Scansiona il Codice QR su WhatsApp',
    'como_deseja_conectar': 'Come vuoi connetterti?',
    'codigo_pareamento': 'Codice di Abbinamento',
    'digite_numero_telefone': 'Inserisci il numero di telefono (con prefisso)',
    'enviando': 'Invio...',
    'obter_codigo_pareamento': 'Ottieni Codice di Abbinamento',
    'digite_codigo_whatsapp': 'Inserisci questo codice su WhatsApp:',
    'configuracoes_aparelhos_conectados': 'Impostazioni → Dispositivi collegati → Collega un dispositivo',
    'sucesso': 'Successo!',
    'canal_adicionado_sucesso': 'Canale aggiunto con successo!',
    'whatsapp_ja_conectado': 'WhatsApp già connesso!',
    'erro_gerar_qr_code': 'Errore nella generazione del Codice QR',
    'erro_criar_instancia': 'Errore nella creazione dell\'istanza',
    'erro_adicionar_canal': 'Errore nell\'aggiunta del canale',
    'erro_excluir_canal': 'Errore nell\'eliminazione del canale',
    'canal_deletado_sucesso': 'Canale eliminato con successo!',
    'erro_deletar_canal': 'Errore nell\'eliminazione del canale',
    'whatsapp_session_desconectado': 'Sessione WhatsApp disconnessa con successo!',
    'erro_desconectar_session': 'Errore nella disconnessione di WhatsApp',
    'whatsapp_desconectado': 'WhatsApp disconnesso con successo!',
    'erro_desconectar_whatsapp': 'Errore nella disconnessione di WhatsApp',
    'detalhes_canal': 'Dettagli Canale',
    'antes_conectar_whatsapp': 'Prima di connettere il tuo WhatsApp:',
    'evitar_bloqueios': 'Per evitare blocchi, assicurati che il tuo numero sia riscaldato!',
    'comece_mensagens_manuais': 'Inizia con messaggi manuali e interazioni reali.',
    'dica': 'Suggerimento:',
    'use_whatsapp_organico': 'Usa WhatsApp in modo organico all\'inizio. Questo crea fiducia ed evita che il tuo numero venga segnalato.',
    'digite_codigo_ou_escaneie': 'Inserisci il codice o scansiona il Codice QR su WhatsApp',
    'usuario_nao_autenticado': 'Utente non autenticato',
    'chatbot_builder': 'Chatbot',
    'planos': 'Piani',
    'gestor_chatbot': 'Gestore Chatbot',
    'criar_novo_fluxo': 'Crea Nuovo Flusso',
    'buscar_fluxos': 'Cerca flussi per nome...',
    'blocos_no_fluxo': 'blocchi nel flusso',
    'atualizado_em': 'Aggiornato il',
    'abrir_no_editor': 'Apri nell\'Editor',
    'novo_fluxo': 'Nuovo Flusso',
    'nome_do_fluxo': 'Nome del Flusso',
    'criar_e_editar': 'Crea e Modifica',
    'fluxo_principal': 'Flusso Principale',
    'nenhum_fluxo_encontrado': 'Nessun flusso trovato',
    'editar_fluxo': 'Modifica Flusso',
    'editar': 'Modifica',
    'deletar': 'Elimina',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Tentar carregar do localStorage
    const savedLanguage = localStorage.getItem('user_language');
    if (savedLanguage) return savedLanguage;

    // Tentar carregar do backend
    const token = localStorage.getItem('token');
    if (token) {
      // Será carregado no useEffect
      return 'pt';
    }

    return 'pt';
  });

  // Carregar idioma do usuário ao montar
  useEffect(() => {
    const loadUserLanguage = async () => {
      try {
        const token = localStorage.getItem('token');
        if (!token) return;

        const response = await axios.get('/api/auth/me/', {
          headers: { Authorization: `Token ${token}` }
        });

        if (response.data.language) {
          setLanguage(response.data.language);
          localStorage.setItem('user_language', response.data.language);
        }
      } catch (error) {
        console.error('Erro ao carregar idioma do usuário:', error);
      }
    };

    loadUserLanguage();
  }, []);

  const changeLanguage = async (newLanguage) => {
    setLanguage(newLanguage);
    localStorage.setItem('user_language', newLanguage);

    // Atualizar no backend
    try {
      const token = localStorage.getItem('token');
      if (token) {
        await axios.patch('/api/auth/me/', {
          language: newLanguage
        }, {
          headers: { Authorization: `Token ${token}` }
        });
      }
    } catch (error) {
      console.error('Erro ao salvar idioma no backend:', error);
    }
  };

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

