# Generated by Django 5.2.4 on 2025-07-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Nio Chat', max_length=100, verbose_name='Nome do Sistema')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='system/', verbose_name='Logo do Sistema')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contato')),
                ('default_language', models.CharField(default='pt-br', max_length=10, verbose_name='Idioma Padrão')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50, verbose_name='Fuso Horário')),
                ('smtp_host', models.CharField(blank=True, max_length=100, null=True, verbose_name='SMTP Host')),
                ('smtp_port', models.IntegerField(blank=True, null=True, verbose_name='SMTP Porta')),
                ('smtp_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='SMTP Usuário')),
                ('smtp_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='SMTP Senha')),
                ('email_from', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Remetente Padrão')),
                ('allow_public_signup', models.BooleanField(default=False, verbose_name='Permitir Cadastro Público')),
                ('max_users_per_company', models.IntegerField(default=10, verbose_name='Limite de Usuários por Empresa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
