# Generated by Django 5.2.4 on 2025-07-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_provedor_identidade_contexto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provedor',
            name='identidade_contexto',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='personalidade_avancada',
        ),
        migrations.AddField(
            model_name='provedor',
            name='informacoes_extras',
            field=models.TextField(blank=True, help_text='Informações extras, regras de fidelidade, integrações RAG, etc', null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='modo_falar',
            field=models.CharField(blank=True, help_text='Modo de falar/sotaque do agente (ex: nordestino, formal, descontraído)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='personalidade',
            field=models.JSONField(blank=True, help_text='Lista de traços de personalidade do agente IA', null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='planos_internet',
            field=models.TextField(blank=True, help_text='Planos de internet oferecidos pela empresa (texto ou JSON)', null=True),
        ),
    ]
