# Generated by Django 5.2.4 on 2025-07-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_provedor_identidade_contexto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provedor',
            name='documentos_necessarios',
            field=models.TextField(blank=True, help_text='Documentos necessários para contratação', null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='emails',
            field=models.JSONField(blank=True, help_text='E-mails de contato: suporte, financeiro, comercial, etc', null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='inclusos_plano',
            field=models.TextField(blank=True, help_text='O que está incluso no plano do cliente', null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='multa_cancelamento',
            field=models.CharField(blank=True, help_text='Multa de cancelamento (sim/não, valor/regra)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações adicionais', null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='prazo_instalacao',
            field=models.CharField(blank=True, help_text='Prazo de instalação após contratação', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='taxa_adesao',
            field=models.CharField(blank=True, help_text='Taxa de adesão (sim/não, valor)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='telefones',
            field=models.JSONField(blank=True, help_text='Telefones de contato: suporte, financeiro, comercial, etc', null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='tipo_conexao',
            field=models.CharField(blank=True, help_text='Tipo de conexão: fibra, rádio, etc', max_length=100, null=True),
        ),
    ]
