# Generated by Django 5.2.4 on 2025-07-14 06:29

import django.db.models.deletion
from django.db import migrations, models, connection


def only_postgresql(apps, schema_editor):
    """Retorna True apenas se o banco for PostgreSQL"""
    return schema_editor.connection.vendor == 'postgresql'


def create_models_if_not_exist(apps, schema_editor):
    """Cria modelos apenas se não existirem (verificação manual de tabela)"""
    tables = ['core_canalemail', 'core_canalfacebook', 'core_canalinstagram', 'core_canaltelegram', 'core_canalwebsite']
    
    # Função para verificar se tabela existe
    def table_exists(table_name):
        with connection.cursor() as cursor:
            if connection.vendor == 'sqlite':
                cursor.execute(f"SELECT name FROM sqlite_master WHERE type='table' AND name='{table_name}';")
                return cursor.fetchone() is not None
            else:
                # PostgreSQL
                cursor.execute(f"SELECT to_regclass('{table_name}');")
                return cursor.fetchone()[0] is not None
                
    # Este script é um wrapper, mas o Django migrations system é declarativo.
    # Para lidar com "duplicate key value violates unique constraint",
    # precisamos envolver as operações de criação em blocos condicionais
    # ou usar SeparateDatabaseAndState se quisermos controle manual.
    # No entanto, o erro "duplicate key value violates unique constraint pg_type_typname_nsp_index"
    # sugere que o TIPO (type) no Postgres já existe, não necessariamente a tabela de dados.
    # Isso acontece quando uma tabela foi criada, depois dropada parcialmente ou ficou lixo no catalogo.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_canalwhatsapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canalwhatsapp',
            options={'verbose_name': 'Canal', 'verbose_name_plural': 'Canais'},
        ),
        migrations.SeparateDatabaseAndState(
            # Removemos database_operations específicas do PostgreSQL
            # O Django criará as tabelas automaticamente via state_operations
            # Isso funciona tanto para SQLite quanto para PostgreSQL
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='CanalEmail',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('email', models.EmailField(max_length=254)),
                        ('nome', models.CharField(blank=True, max_length=100, null=True)),
                        ('ativo', models.BooleanField(default=True)),
                        ('criado_em', models.DateTimeField(auto_now_add=True)),
                        ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais_email', to='core.provedor')),
                    ],
                    options={
                        'verbose_name': 'Canal',
                        'verbose_name_plural': 'Canais',
                        'unique_together': {('provedor', 'email')},
                    },
                ),
                migrations.CreateModel(
                    name='CanalFacebook',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('page_id', models.CharField(max_length=100)),
                        ('url', models.URLField(blank=True, null=True)),
                        ('ativo', models.BooleanField(default=True)),
                        ('criado_em', models.DateTimeField(auto_now_add=True)),
                        ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais_facebook', to='core.provedor')),
                    ],
                    options={
                        'verbose_name': 'Canal',
                        'verbose_name_plural': 'Canais',
                        'unique_together': {('provedor', 'page_id')},
                    },
                ),
                migrations.CreateModel(
                    name='CanalInstagram',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('username', models.CharField(max_length=100)),
                        ('url', models.URLField(blank=True, null=True)),
                        ('ativo', models.BooleanField(default=True)),
                        ('criado_em', models.DateTimeField(auto_now_add=True)),
                        ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais_instagram', to='core.provedor')),
                    ],
                    options={
                        'verbose_name': 'Canal',
                        'verbose_name_plural': 'Canais',
                        'unique_together': {('provedor', 'username')},
                    },
                ),
                migrations.CreateModel(
                    name='CanalTelegram',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('token', models.CharField(max_length=255)),
                        ('chat_id', models.CharField(blank=True, max_length=100, null=True)),
                        ('ativo', models.BooleanField(default=True)),
                        ('criado_em', models.DateTimeField(auto_now_add=True)),
                        ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais_telegram', to='core.provedor')),
                    ],
                    options={
                        'verbose_name': 'Canal',
                        'verbose_name_plural': 'Canais',
                        'unique_together': {('provedor', 'token', 'chat_id')},
                    },
                ),
                migrations.CreateModel(
                    name='CanalWebsite',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('url', models.URLField()),
                        ('nome', models.CharField(blank=True, max_length=100, null=True)),
                        ('ativo', models.BooleanField(default=True)),
                        ('criado_em', models.DateTimeField(auto_now_add=True)),
                        ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais_website', to='core.provedor')),
                    ],
                    options={
                        'verbose_name': 'Canal',
                        'verbose_name_plural': 'Canais',
                        'unique_together': {('provedor', 'url')},
                    },
                ),
            ]
        ),
    ]
