# Generated by Django 5.2.4 on 2025-07-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_canalfacebook_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='canal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='canal',
            name='api_hash',
            field=models.CharField(blank=True, help_text='App api_hash (Telegram)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='canal',
            name='api_id',
            field=models.CharField(blank=True, help_text='App api_id (Telegram)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='canal',
            name='app_title',
            field=models.CharField(blank=True, help_text='App title (Telegram)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='canal',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short name (Telegram)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='canal',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='SMTP Host (Email)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='canal',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='SMTP Senha (Email)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='canal',
            name='smtp_port',
            field=models.CharField(blank=True, help_text='SMTP Porta (Email)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='canal',
            name='smtp_user',
            field=models.CharField(blank=True, help_text='SMTP Usuário (Email)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='email',
            field=models.EmailField(blank=True, help_text='E-mail (SMTP)', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome da Instância (Evolution)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='page_id',
            field=models.CharField(blank=True, help_text='Page ID (Facebook)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='token',
            field=models.CharField(blank=True, help_text='API Key (Evolution)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='url',
            field=models.URLField(blank=True, help_text='URL da API (Evolution, Website, Facebook, Instagram)', null=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='username',
            field=models.CharField(blank=True, help_text='Username (Instagram/Facebook)', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='canal',
            unique_together={('provedor', 'tipo', 'nome', 'token', 'url', 'api_id', 'api_hash', 'app_title', 'short_name', 'email', 'smtp_host', 'smtp_port', 'smtp_user', 'smtp_password', 'username', 'page_id', 'chat_id')},
        ),
    ]
