# Generated by Django 5.2.4 on 2025-07-16 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_canal_unique_together_canal_api_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='provedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='core.provedor', verbose_name='Provedor'),
        ),
    ]
