# Generated by Django 5.2.4 on 2025-07-17 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_label_unique_together_label_provedor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('name', 'provedor')},
        ),
        migrations.RemoveField(
            model_name='label',
            name='company',
        ),
    ]
