# Generated by Django 5.2.4 on 2025-07-20 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_user_permissions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='canal',
            unique_together=set(),
        ),
    ]
