# Generated by Django 5.2.4 on 2025-07-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_canal_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canal',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='canal',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='canal',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='canal',
            name='smtp_password',
        ),
        migrations.RemoveField(
            model_name='canal',
            name='smtp_user',
        ),
        migrations.RemoveField(
            model_name='canal',
            name='token',
        ),
        migrations.RemoveField(
            model_name='canal',
            name='username',
        ),
        migrations.AddField(
            model_name='canal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='api_hash',
            field=models.CharField(blank=True, help_text='App API Hash do Telegram', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='api_id',
            field=models.CharField(blank=True, help_text='App API ID do Telegram', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='app_title',
            field=models.CharField(blank=True, help_text='App Title do Telegram', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short Name do Telegram', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='smtp_port',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='tipo',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'E-mail'), ('website', 'Website'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20),
        ),
        migrations.AlterField(
            model_name='canal',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
