# Generated by Django 5.2.4 on 2025-07-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_canal_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='dados_extras',
            field=models.JSONField(blank=True, help_text='Dados extras do canal (instance_id, etc)', null=True),
        ),
    ]
