# Generated by Django 5.2.4 on 2025-08-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_canal_dados_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='provedor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
