# Generated by Django 5.2.4 on 2025-08-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_provedor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='provedor',
            name='planos_descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada dos planos oferecidos pela empresa', null=True),
        ),
    ]
