# Generated by Django 5.2.4 on 2025-08-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_openai_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='provedor',
            name='ferramentas_ia',
            field=models.JSONField(blank=True, help_text='Ferramentas personalizadas para o agente IA', null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='fluxo_atendimento',
            field=models.JSONField(blank=True, help_text='Fluxo de atendimento personalizado para o agente IA', null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='regras_gerais',
            field=models.JSONField(blank=True, help_text='Regras gerais personalizadas para o agente IA', null=True),
        ),
    ]
