# Generated by Django 5.2.4 on 2025-08-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_provedor_ferramentas_ia_provedor_fluxo_atendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='channel_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Canal'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Contato'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='conversation_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duração da Conversa'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='conversation_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID da Conversa'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='message_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Mensagens'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resolution_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Resolução'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('edit', 'Edição'), ('create', 'Criação'), ('delete', 'Exclusão'), ('conversation_closed_agent', 'Conversa Encerrada por Atendente'), ('conversation_closed_ai', 'Conversa Encerrada por IA'), ('conversation_transferred', 'Conversa Transferida'), ('conversation_assigned', 'Conversa Atribuída'), ('other', 'Outro')], max_length=30),
        ),
    ]
