# Generated by Django 5.2.4 on 2025-08-19 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_limpezadadosprovedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LimpezaDadosProvedor',
        ),
    ]
