# Generated by Django 5.2.4 on 2025-08-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_mensagemsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='provedor',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento'),
        ),
        migrations.AddField(
            model_name='provedor',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento'),
        ),
        migrations.AddField(
            model_name='provedor',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('cancelado', 'Cancelado'), ('suspenso', 'Suspenso'), ('pendente', 'Pendente'), ('bloqueado', 'Bloqueado')], default='ativo', max_length=20, verbose_name='Status'),
        ),
    ]
