# Generated by Django 5.2.4 on 2025-08-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_provedor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provedor',
            name='data_cancelamento',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='motivo_cancelamento',
        ),
        migrations.AddField(
            model_name='provedor',
            name='data_suspensao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Suspensão'),
        ),
        migrations.AddField(
            model_name='provedor',
            name='motivo_suspensao',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Suspensão'),
        ),
        migrations.AlterField(
            model_name='provedor',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso')], default='ativo', max_length=20, verbose_name='Status'),
        ),
    ]
