# Generated by Django 5.2.4 on 2025-08-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_simplify_provedor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provedor',
            name='dados_adicionais',
            field=models.TextField(blank=True, help_text='Dados adicionais relevantes para o atendimento', null=True),
        ),
    ]
