# Generated by Django 5.2.4 on 2025-08-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_systemconfig_key_alter_systemconfig_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='provedor',
            name='documentos_necessarios',
            field=models.TextField(blank=True, help_text='Documentos necessários para cadastro', null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='email_contato',
            field=models.EmailField(blank=True, help_text='E-mail de contato do provedor', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='modo_falar',
            field=models.CharField(blank=True, help_text='Ex: Nordestino, Formal, Descontraído', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='multa_cancelamento',
            field=models.CharField(blank=True, help_text='Multa de cancelamento', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='personalidade',
            field=models.JSONField(blank=True, help_text='Personalidade avançada: vicios_linguagem, caracteristicas, principios, humor', null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='planos_descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada dos planos', null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='planos_internet',
            field=models.TextField(blank=True, help_text='Planos de internet oferecidos', null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='prazo_instalacao',
            field=models.CharField(blank=True, help_text='Prazo de instalação', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='taxa_adesao',
            field=models.CharField(blank=True, help_text='Taxa de adesão', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='tipo_conexao',
            field=models.CharField(blank=True, help_text='Tipo de conexão', max_length=100, null=True),
        ),
    ]
