# Generated by Django 5.2.4 on 2025-09-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_user_new_conversation_sound_user_new_message_sound_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_timeout',
            field=models.IntegerField(default=30, verbose_name='Timeout da Sessão (minutos)'),
        ),
    ]
