# Generated by Django 5.2.4 on 2025-11-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_canal_phone_number_id_canal_status_canal_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('pt', 'Português'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('it', 'Italiano')], default='pt', max_length=10, verbose_name='Idioma do Sistema'),
        ),
        migrations.AlterField(
            model_name='canal',
            name='tipo',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('whatsapp_session', 'WhatsApp QR code'), ('telegram', 'Telegram'), ('email', 'Email'), ('webchat', 'WebChat')], default='whatsapp', max_length=50),
        ),
    ]
