# Generated by Django 5.2.4 on 2025-11-30 16:19

from django.db import migrations, models, connection


def add_assignment_message_if_not_exists(apps, schema_editor):
    """Adiciona o campo assignment_message apenas se não existir"""
    table_name = 'core_user'
    column_name = 'assignment_message'
    
    with connection.cursor() as cursor:
        # Detectar se a coluna existe
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name=%s AND column_name=%s
            """, [table_name, column_name])
            exists = cursor.fetchone() is not None
        elif connection.vendor == 'sqlite':
            cursor.execute(f"PRAGMA table_info({table_name})")
            columns = [row[1] for row in cursor.fetchall()]
            exists = column_name in columns
        else:
            # Fallback para outros bancos (tentar selecionar)
            try:
                cursor.execute(f"SELECT {column_name} FROM {table_name} LIMIT 1")
                exists = True
            except Exception:
                exists = False

        if not exists:
            # Adicionar a coluna
            if connection.vendor == 'postgresql':
                cursor.execute(f"ALTER TABLE {table_name} ADD COLUMN {column_name} TEXT")
            else:
                # SQLite e outros
                cursor.execute(f"ALTER TABLE {table_name} ADD COLUMN {column_name} TEXT")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_add_mensagem_sistema_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='mensagemsistema',
                    name='assunto',
                    field=models.CharField(blank=True, default='', max_length=200, verbose_name='Assunto'),
                ),
                migrations.AddField(
                    model_name='mensagemsistema',
                    name='mensagem',
                    field=models.TextField(blank=True, default='', verbose_name='Mensagem'),
                ),
                migrations.AddField(
                    model_name='mensagemsistema',
                    name='provedores',
                    field=models.JSONField(default=list, verbose_name='Provedores (IDs)'),
                ),
                migrations.AddField(
                    model_name='mensagemsistema',
                    name='provedores_count',
                    field=models.IntegerField(default=0, verbose_name='Quantidade de Provedores'),
                ),
                migrations.AddField(
                    model_name='mensagemsistema',
                    name='visualizacoes',
                    field=models.JSONField(default=dict, verbose_name='Visualizações'),
                ),
                migrations.AddField(
                    model_name='mensagemsistema',
                    name='visualizacoes_count',
                    field=models.IntegerField(default=0, verbose_name='Quantidade de Visualizações'),
                ),
            ]
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_assignment_message_if_not_exists),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='assignment_message',
                    field=models.TextField(blank=True, help_text='Mensagem enviada automaticamente ao atribuir um atendimento a este usuário', null=True, verbose_name='Mensagem de Atribuição'),
                ),
            ]
        ),
        migrations.AlterField(
            model_name='mensagemsistema',
            name='conteudo',
            field=models.TextField(blank=True, default='', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='mensagemsistema',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Título'),
        ),
    ]
