# Generated by Django 5.2.4 on 2025-12-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_add_mensagem_sistema_fields_sqlite'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='openai_transcription_api_key',
            field=models.CharField(blank=True, help_text='Chave da API OpenAI exclusivamente para transcrição de áudio. Não será usada para geração de respostas.', max_length=255, null=True, verbose_name='OpenAI Transcription API Key'),
        ),
    ]
