# Generated by Django
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_provedor_asaas_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='provedor',
            name='asaas_subscription_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Asaas Subscription ID'),
        ),
        migrations.AddField(
            model_name='provedor',
            name='subscription_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Mensalidade'),
        ),
        migrations.AddField(
            model_name='provedor',
            name='subscription_cycle',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ciclo de Faturamento'),
        ),
        migrations.AddField(
            model_name='provedor',
            name='subscription_billing_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='provedor',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status da Assinatura'),
        ),
        migrations.AddField(
            model_name='provedor',
            name='block_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Bloqueio'),
        ),
    ]
