# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_systemconfig_billing_channel_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="billing_whatsapp_use_template",
            field=models.BooleanField(
                default=True,
                verbose_name="Usar template Meta na automação de cobrança",
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="billing_whatsapp_template_name",
            field=models.CharField(
                max_length=120,
                default="cobranca_order",
                blank=True,
                verbose_name="Nome do template Meta (cobrança)",
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="billing_whatsapp_template_language",
            field=models.CharField(
                max_length=20,
                default="pt_BR",
                blank=True,
                verbose_name="Idioma do template (cobrança)",
            ),
        ),
    ]
