# Generated by Django 5.2.4 on 2025-07-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('yahoo', 'Yahoo'), ('custom', 'Personalizado')], default='gmail', max_length=20, verbose_name='Provedor')),
                ('imap_host', models.CharField(max_length=200, verbose_name='Servidor IMAP')),
                ('imap_port', models.IntegerField(default=993, verbose_name='Porta IMAP')),
                ('imap_use_ssl', models.BooleanField(default=True, verbose_name='IMAP SSL')),
                ('smtp_host', models.CharField(max_length=200, verbose_name='Servidor SMTP')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='Porta SMTP')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='SMTP TLS')),
                ('username', models.CharField(max_length=200, verbose_name='Usuário')),
                ('password', models.CharField(max_length=200, verbose_name='Senha')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('is_connected', models.BooleanField(default=False, verbose_name='Conectado')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Configurações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_integrations', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Integração E-mail',
                'verbose_name_plural': 'Integrações E-mail',
            },
        ),
        migrations.CreateModel(
            name='TelegramIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=100, verbose_name='API ID')),
                ('api_hash', models.CharField(max_length=100, verbose_name='API Hash')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de Telefone')),
                ('session_string', models.TextField(blank=True, null=True, verbose_name='String de Sessão')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('is_connected', models.BooleanField(default=False, verbose_name='Conectado')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Configurações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_integration', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Integração Telegram',
                'verbose_name_plural': 'Integrações Telegram',
            },
        ),
        migrations.CreateModel(
            name='WebchatIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_color', models.CharField(default='#007bff', max_length=7, verbose_name='Cor do Widget')),
                ('welcome_message', models.TextField(default='Olá! Como podemos ajudá-lo?', verbose_name='Mensagem de Boas-vindas')),
                ('pre_chat_form_enabled', models.BooleanField(default=True, verbose_name='Formulário Pré-chat Habilitado')),
                ('pre_chat_form_options', models.JSONField(blank=True, default=dict, verbose_name='Opções do Formulário Pré-chat')),
                ('business_hours', models.JSONField(blank=True, default=dict, verbose_name='Horário de Funcionamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Configurações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webchat_integration', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Integração Chat Web',
                'verbose_name_plural': 'Integrações Chat Web',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de Telefone')),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='URL do Webhook')),
                ('access_token', models.CharField(blank=True, max_length=500, null=True, verbose_name='Token de Acesso')),
                ('verify_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='Token de Verificação')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('is_connected', models.BooleanField(default=False, verbose_name='Conectado')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Configurações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_integration', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Integração WhatsApp',
                'verbose_name_plural': 'Integrações WhatsApp',
            },
        ),
    ]
