# Generated by Django 6.0.2 on 2026-05-01 03:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(default='UTILITY', max_length=30)),
                ('language', models.CharField(default='pt_BR', max_length=20)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('body_text', models.TextField(blank=True, default='')),
                ('components', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MensagemSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(blank=True, default='', max_length=200)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('provedores', models.JSONField(blank=True, default=list)),
                ('tipo', models.CharField(default='notificacao', max_length=30)),
                ('visivel_para_agentes', models.BooleanField(default=True)),
                ('visualizacoes', models.JSONField(blank=True, default=dict)),
                ('visualizacoes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('site_oficial', models.URLField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=300, null=True)),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True)),
                ('bot_mode', models.CharField(default='ia', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(default='ativo', max_length=30)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address_number', models.CharField(blank=True, max_length=30, null=True)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('municipal_inscription', models.CharField(blank=True, max_length=50, null=True)),
                ('state_inscription', models.CharField(blank=True, max_length=50, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('additional_emails', models.TextField(blank=True, null=True)),
                ('notification_disabled', models.BooleanField(default=False)),
                ('foreign_customer', models.BooleanField(default=False)),
                ('asaas_customer_id', models.CharField(blank=True, max_length=60, null=True)),
                ('asaas_subscription_id', models.CharField(blank=True, max_length=60, null=True)),
                ('subscription_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subscription_cycle', models.CharField(blank=True, default='MONTHLY', max_length=20, null=True)),
                ('subscription_billing_type', models.CharField(blank=True, default='BOLETO', max_length=30, null=True)),
                ('subscription_status', models.CharField(blank=True, default='PENDING', max_length=30, null=True)),
                ('subscription_next_due_date', models.DateField(blank=True, null=True)),
                ('redes_sociais', models.JSONField(blank=True, default=dict)),
                ('nome_agente_ia', models.CharField(blank=True, max_length=100, null=True)),
                ('estilo_personalidade', models.CharField(blank=True, max_length=60, null=True)),
                ('modo_falar', models.CharField(blank=True, max_length=100, null=True)),
                ('uso_emojis', models.CharField(blank=True, max_length=20, null=True)),
                ('personalidade', models.TextField(blank=True, null=True)),
                ('taxa_adesao', models.CharField(blank=True, max_length=100, null=True)),
                ('inclusos_plano', models.TextField(blank=True, null=True)),
                ('multa_cancelamento', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_conexao', models.CharField(blank=True, max_length=100, null=True)),
                ('prazo_instalacao', models.CharField(blank=True, max_length=100, null=True)),
                ('documentos_necessarios', models.TextField(blank=True, null=True)),
                ('users_count', models.IntegerField(default=0)),
                ('conversations_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('agent', 'Atendente')], default='agent', max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('session_timeout', models.IntegerField(default=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('provedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='super_core.provedor')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='view', max_length=60)),
                ('details', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('tipo', models.CharField(default='telegram', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('dados_extras', models.JSONField(blank=True, default=dict)),
                ('instance_id', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_id', models.CharField(blank=True, max_length=255, null=True)),
                ('api_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('app_title', models.CharField(blank=True, max_length=200, null=True)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.CharField(blank=True, max_length=10, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais', to='super_core.provedor')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
