# Generated by Django 6.0.2 on 2026-05-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provedor',
            name='integracoes_externas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
