# Generated by Django 6.0.2 on 2026-05-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_core', '0002_provedor_integracoes_externas'),
    ]

    operations = [
        migrations.AddField(
            model_name='provedor',
            name='subdomain',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
