# Generated by Django 6.0.2 on 2026-05-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_core', '0003_provedor_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpsServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_url', models.URLField(help_text='Ex: https://vps1.niohub.com.br:9443')),
                ('portainer_api_key', models.CharField(max_length=255)),
                ('endpoint_id', models.IntegerField(default=1)),
                ('max_capacity', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servidor VPS',
                'verbose_name_plural': 'Servidores VPS',
            },
        ),
        migrations.AddField(
            model_name='provedor',
            name='vps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provedores', to='super_core.vpsserver'),
        ),
    ]
