# Generated by Django 6.0.2 on 2026-05-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_core', '0004_vpsserver_provedor_vps'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpsserver',
            name='rabbitmq_url',
            field=models.CharField(default='amqp://guest:guest@localhost:5672/', max_length=255),
        ),
        migrations.AddField(
            model_name='vpsserver',
            name='redis_host',
            field=models.CharField(default='localhost', max_length=255),
        ),
        migrations.AddField(
            model_name='vpsserver',
            name='redis_password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
