# Generated by Django 6.0.2 on 2026-05-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_core', '0005_vpsserver_rabbitmq_url_vpsserver_redis_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(choices=[('beta', 'Beta (Atualização Automática)'), ('stable', 'Estável (Atualização Controlada)'), ('manual', 'Manual')], max_length=20)),
                ('is_deployed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.AddField(
            model_name='provedor',
            name='current_version',
            field=models.CharField(default='1.0.0', max_length=50),
        ),
        migrations.AddField(
            model_name='provedor',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='release_channel',
            field=models.CharField(choices=[('beta', 'Beta (Atualização Automática)'), ('stable', 'Estável (Atualização Controlada)'), ('manual', 'Manual')], default='stable', max_length=20),
        ),
        migrations.AlterField(
            model_name='provedor',
            name='integracoes_externas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
