# Generated by Django 6.0.2 on 2026-05-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_core', '0006_systemupdate_provedor_current_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='phone_number_id',
            field=models.CharField(blank=True, db_index=True, help_text='Phone Number ID da Meta', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='canal',
            name='waba_id',
            field=models.CharField(blank=True, db_index=True, help_text='WhatsApp Business Account ID', max_length=100, null=True),
        ),
    ]
