# Generated by Django 5.2.4 on 2025-07-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaProvedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_provedor', models.CharField(max_length=200)),
                ('nome_agente_ia', models.CharField(max_length=100)),
                ('horarios_atendimento', models.TextField(blank=True, help_text='Horários de atendimento (texto ou JSON)', null=True)),
                ('dias_atendimento', models.TextField(blank=True, help_text='Dias de atendimento (texto ou JSON)', null=True)),
                ('planos', models.TextField(blank=True, help_text='Planos da empresa (texto ou JSON)', null=True)),
                ('redes_sociais', models.JSONField(blank=True, help_text='Redes sociais da empresa', null=True)),
                ('site_oficial', models.URLField(blank=True, null=True)),
                ('dados_adicionais', models.TextField(blank=True, help_text='FAQ, orientações, termos, políticas, etc', null=True)),
                ('integracoes_externas', models.JSONField(blank=True, help_text='Dados de integração com SGP/URA: app, token, endpoints personalizados', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa Provedora',
                'verbose_name_plural': 'Empresas Provedoras',
            },
        ),
    ]
