# Generated by Django 5.2.4 on 2025-07-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empresaprovedora'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaprovedora',
            name='avatar_agente',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='empresaprovedora',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='empresaprovedora',
            name='estilo_personalidade',
            field=models.CharField(blank=True, help_text='Ex: Formal, Brincalhão, Educado', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresaprovedora',
            name='personalidade_avancada',
            field=models.JSONField(blank=True, help_text='Campos: vicios_linguagem, caracteristicas, principios, humor', null=True),
        ),
        migrations.AddField(
            model_name='empresaprovedora',
            name='uso_emojis',
            field=models.CharField(blank=True, help_text='sempre, ocasionalmente, nunca', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empresaprovedora',
            name='nome_agente_ia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
