# Generated by Django 5.2.4 on 2025-07-13 23:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresaprovedora_avatar_agente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('site_oficial', models.URLField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=300, null=True)),
                ('redes_sociais', models.JSONField(blank=True, help_text='Redes sociais da empresa', null=True)),
                ('horarios_atendimento', models.TextField(blank=True, help_text='Horários de atendimento (texto ou JSON)', null=True)),
                ('dias_atendimento', models.TextField(blank=True, help_text='Dias de atendimento (texto ou JSON)', null=True)),
                ('planos', models.TextField(blank=True, help_text='Planos da empresa (texto ou JSON)', null=True)),
                ('dados_adicionais', models.TextField(blank=True, help_text='FAQ, orientações, termos, políticas, etc', null=True)),
                ('integracoes_externas', models.JSONField(blank=True, help_text='Dados de integração com SGP/URA: app, token, endpoints personalizados', null=True)),
                ('nome_agente_ia', models.CharField(blank=True, max_length=100, null=True)),
                ('estilo_personalidade', models.CharField(blank=True, help_text='Ex: Formal, Brincalhão, Educado', max_length=50, null=True)),
                ('uso_emojis', models.CharField(blank=True, help_text='sempre, ocasionalmente, nunca', max_length=20, null=True)),
                ('personalidade_avancada', models.JSONField(blank=True, help_text='Campos: vicios_linguagem, caracteristicas, principios, humor', null=True)),
                ('avatar_agente', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admins', models.ManyToManyField(blank=True, help_text='Usuários administradores deste provedor', related_name='provedores_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provedor',
                'verbose_name_plural': 'Provedores',
            },
        ),
        migrations.DeleteModel(
            name='EmpresaProvedora',
        ),
    ]
