# Generated by Django 5.2.4 on 2025-07-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_provedor_delete_empresaprovedora'),
    ]

    operations = [
        migrations.AddField(
            model_name='provedor',
            name='identidade_contexto',
            field=models.TextField(blank=True, help_text='Prompt base/contexto do agente IA', null=True),
        ),
    ]
