# Generated by Django 5.2.4 on 2025-07-14 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_provedor_documentos_necessarios_provedor_emails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('evolution', 'Evolution'), ('uazapi', 'Uazapi.dev')], max_length=20)),
                ('token', models.CharField(max_length=255)),
                ('url_api', models.URLField()),
                ('nome_instancia', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais_whatsapp', to='core.provedor')),
            ],
            options={
                'verbose_name': 'Canal WhatsApp',
                'verbose_name_plural': 'Canais WhatsApp',
                'unique_together': {('provedor', 'tipo', 'nome_instancia')},
            },
        ),
    ]
