# Generated by Django 5.2.4 on 2025-07-14 06:34

import django.db.models.deletion
from django.db import migrations, models, connection


def remove_unique_together_if_exists(apps, schema_editor):
    """Remove unique_together apenas se a tabela existir no banco"""
    tables_to_check = {
        'canalfacebook': 'core_canalfacebook',
        'canalinstagram': 'core_canalinstagram',
        'canaltelegram': 'core_canaltelegram',
        'canalwebsite': 'core_canalwebsite',
        'canalwhatsapp': 'core_canalwhatsapp'
    }
    
    def table_exists(table_name):
        with connection.cursor() as cursor:
            if connection.vendor == 'sqlite':
                cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name=?;", [table_name])
                return cursor.fetchone() is not None
            else:
                # PostgreSQL
                cursor.execute("SELECT to_regclass(%s);", [table_name])
                result = cursor.fetchone()
                return result and result[0] is not None
    
    # Não fazemos nada aqui - as tabelas podem não existir
    # A remoção do unique_together será feita apenas no state
    pass


def reverse_remove_unique_together(apps, schema_editor):
    """Função reversa - não faz nada"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_canalwhatsapp_options_canalemail_canalfacebook_and_more'),
    ]

    operations = [
        # Usar RunPython para garantir que não haja erros se as tabelas não existirem
        migrations.RunPython(
            remove_unique_together_if_exists,
            reverse_remove_unique_together,
        ),
        # Usar SeparateDatabaseAndState porque as tabelas podem não existir no banco
        # (a migração 0011 só criou no state, não no banco devido ao SeparateDatabaseAndState)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                # Remover unique_together e campos dos modelos antigos (apenas no state)
                migrations.AlterUniqueTogether(
                    name='canalfacebook',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='canalfacebook',
                    name='provedor',
                ),
                migrations.AlterUniqueTogether(
                    name='canalinstagram',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='canalinstagram',
                    name='provedor',
                ),
                migrations.AlterUniqueTogether(
                    name='canaltelegram',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='canaltelegram',
                    name='provedor',
                ),
                migrations.AlterUniqueTogether(
                    name='canalwebsite',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='canalwebsite',
                    name='provedor',
                ),
                migrations.AlterUniqueTogether(
                    name='canalwhatsapp',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='canalwhatsapp',
                    name='provedor',
                ),
            ]
        ),
        # Criar o novo modelo Canal (será criado no banco normalmente)
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email'), ('website', 'Website'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('page_id', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais', to='core.provedor')),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canais',
                'unique_together': {('provedor', 'tipo', 'username', 'email', 'url', 'page_id', 'chat_id')},
            },
        ),
        # Remover os modelos antigos (apenas no state, já que podem não existir no banco)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='CanalEmail',
                ),
                migrations.DeleteModel(
                    name='CanalFacebook',
                ),
                migrations.DeleteModel(
                    name='CanalInstagram',
                ),
                migrations.DeleteModel(
                    name='CanalTelegram',
                ),
                migrations.DeleteModel(
                    name='CanalWebsite',
                ),
                migrations.DeleteModel(
                    name='CanalWhatsapp',
                ),
            ]
        ),
    ]
