# Generated by Django 5.2.4 on 2025-07-17 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_label_unique_together_remove_label_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='provedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.provedor', verbose_name='Provedor'),
        ),
    ]
