# Generated by Django 5.2.4 on 2025-07-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_provedor_to_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.JSONField(blank=True, default=list, verbose_name='Permissões Específicas'),
        ),
    ]
