# Generated by Django 5.2.4 on 2025-07-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_criado_em_canal_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='verification_code',
            field=models.CharField(blank=True, help_text='Código de verificação do Telegram', max_length=10, null=True),
        ),
    ]
