# Generated by Django 5.2.4 on 2025-07-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_canal_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Número de telefone do Telegram', max_length=20, null=True),
        ),
    ]
