# Generated by Django 5.2.4 on 2025-07-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_canal_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='sgp_app',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='App do SGP'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='sgp_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token do SGP'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='sgp_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL do SGP'),
        ),
    ]
