# Generated by Django 5.2.4 on 2025-07-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_systemconfig_sgp_app_systemconfig_sgp_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='tipo',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('whatsapp_session', 'WhatsApp session'), ('telegram', 'Telegram'), ('email', 'E-mail'), ('website', 'Website'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20),
        ),
    ]
