# Generated by Django 5.2.4 on 2025-08-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_planos_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave da API OpenAI'),
        ),
    ]
