# Generated by Django 5.2.4 on 2025-08-15 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auditlog_channel_type_auditlog_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimpezaDadosProvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_limpeza', models.CharField(choices=[('redis', 'Apenas Redis'), ('banco', 'Apenas Banco de Dados'), ('completa', 'Redis + Banco de Dados')], default='completa', max_length=20, verbose_name='Tipo de Limpeza')),
                ('executado_em', models.DateTimeField(auto_now_add=True, verbose_name='Executado em')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_execucao', 'Em Execução'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhes da Execução')),
                ('chaves_redis_removidas', models.IntegerField(default=0, verbose_name='Chaves Redis Removidas')),
                ('registros_banco_removidos', models.IntegerField(default=0, verbose_name='Registros do Banco Removidos')),
                ('executado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Executado por')),
                ('provedor', models.ForeignKey(help_text='Provedor cujos dados serão limpos', on_delete=django.db.models.deletion.CASCADE, to='core.provedor', verbose_name='Provedor')),
            ],
            options={
                'verbose_name': 'Limpeza de Dados do Provedor',
                'verbose_name_plural': 'Limpezas de Dados dos Provedores',
                'ordering': ['-executado_em'],
            },
        ),
    ]
