# Generated by Django 5.2.4 on 2025-08-23 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_delete_limpezadadosprovedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provedor',
            field=models.ForeignKey(blank=True, help_text='Provedor ao qual o usuário pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.provedor', verbose_name='Provedor'),
        ),
    ]
