# Generated by Django 5.2.4 on 2025-08-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_user_provedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('notificacao', 'Notificação'), ('aviso', 'Aviso'), ('manutencao', 'Manutenção')], default='notificacao', max_length=20)),
                ('provedores', models.JSONField(default=list)),
                ('provedores_count', models.IntegerField(default=0)),
                ('visualizacoes', models.JSONField(default=dict)),
                ('visualizacoes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensagem do Sistema',
                'verbose_name_plural': 'Mensagens do Sistema',
                'ordering': ['-created_at'],
            },
        ),
    ]
