# Generated by Django 5.2.4 on 2025-08-30 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_provedor_dados_adicionais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provedor',
            name='dados_adicionais',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='dias_atendimento',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='documentos_necessarios',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='horarios_atendimento',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='inclusos_plano',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='informacoes_extras',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='multa_cancelamento',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='planos',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='prazo_instalacao',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='taxa_adesao',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='telefones',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='tipo_conexao',
        ),
    ]
