# Generated by Django 5.2.4 on 2025-08-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_provedor_dados_adicionais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provedor',
            name='documentos_necessarios',
            field=models.TextField(blank=True, help_text='Documentos necessários para contratação', null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='multa_cancelamento',
            field=models.CharField(blank=True, help_text='Multa de cancelamento (sim/não, valor/regra)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='prazo_instalacao',
            field=models.CharField(blank=True, help_text='Prazo de instalação após contratação', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='taxa_adesao',
            field=models.CharField(blank=True, help_text='Taxa de adesão (sim/não, valor)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='tipo_conexao',
            field=models.CharField(blank=True, help_text='Tipo de conexão: fibra, rádio, etc', max_length=100, null=True),
        ),
    ]
