# Generated by Django 5.2.4 on 2025-08-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_provedor_documentos_necessarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='csat_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Avaliação CSAT (1-5)'),
        ),
    ]
