# Generated by Django 5.2.4 on 2025-08-31 12:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_csat_to_auditlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='conversation_duration',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='message_count',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='resolution_type',
        ),
        migrations.RemoveField(
            model_name='canal',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='canal',
            name='app_title',
        ),
        migrations.RemoveField(
            model_name='canal',
            name='email',
        ),
        migrations.RemoveField(
            model_name='canal',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='canal',
            name='smtp_host',
        ),
        migrations.RemoveField(
            model_name='canal',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='canal',
            name='url',
        ),
        migrations.RemoveField(
            model_name='mensagemsistema',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='mensagemsistema',
            name='mensagem',
        ),
        migrations.RemoveField(
            model_name='mensagemsistema',
            name='provedores',
        ),
        migrations.RemoveField(
            model_name='mensagemsistema',
            name='provedores_count',
        ),
        migrations.RemoveField(
            model_name='mensagemsistema',
            name='visualizacoes',
        ),
        migrations.RemoveField(
            model_name='mensagemsistema',
            name='visualizacoes_count',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='data_suspensao',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='documentos_necessarios',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='ferramentas_ia',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='fluxo_atendimento',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='modo_falar',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='motivo_suspensao',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='multa_cancelamento',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='personalidade',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='planos_descricao',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='planos_internet',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='prazo_instalacao',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='regras_gerais',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='status',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='taxa_adesao',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='tipo_conexao',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='allow_public_signup',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='default_language',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='email_from',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='max_users_per_company',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='openai_api_key',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='site_logo',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='smtp_host',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='smtp_password',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='smtp_user',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='provedor',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AddField(
            model_name='label',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='mensagemsistema',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AddField(
            model_name='mensagemsistema',
            name='conteudo',
            field=models.TextField(default='', verbose_name='Conteúdo'),
        ),
        migrations.AddField(
            model_name='mensagemsistema',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AddField(
            model_name='mensagemsistema',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='mensagemsistema',
            name='provedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_sistema', to='core.provedor', verbose_name='Provedor'),
        ),
        migrations.AddField(
            model_name='mensagemsistema',
            name='titulo',
            field=models.CharField(default='', max_length=200, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='provedor',
            name='dados_adicionais',
            field=models.TextField(blank=True, help_text='FAQ, orientações, termos, políticas, etc', null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='dias_atendimento',
            field=models.TextField(blank=True, help_text='Dias de atendimento (texto ou JSON)', null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='horarios_atendimento',
            field=models.TextField(blank=True, help_text='Horários de atendimento (texto ou JSON)', null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='personalidade_avancada',
            field=models.JSONField(blank=True, help_text='Campos: vicios_linguagem, caracteristicas, principios, humor', null=True),
        ),
        migrations.AddField(
            model_name='provedor',
            name='planos',
            field=models.TextField(blank=True, help_text='Planos da empresa (texto ou JSON)', null=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='key',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Chave'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='value',
            field=models.TextField(default='', verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Criar'), ('edit', 'Editar'), ('delete', 'Deletar'), ('view', 'Visualizar'), ('export', 'Exportar'), ('import', 'Importar'), ('transfer', 'Transferir'), ('close', 'Fechar'), ('open', 'Abrir'), ('assign', 'Atribuir')], max_length=50, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Conversa'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='csat_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Avaliação CSAT'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.TextField(default='', verbose_name='Detalhes'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='provedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.provedor', verbose_name='Provedor'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora'),
        ),
        migrations.AlterField(
            model_name='canal',
            name='api_hash',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Hash da API'),
        ),
        migrations.AlterField(
            model_name='canal',
            name='dados_extras',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='canal',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='canal',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='tipo',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('whatsapp_session', 'WhatsApp session'), ('telegram', 'Telegram'), ('email', 'Email'), ('webchat', 'WebChat'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], default='whatsapp', max_length=50),
        ),
        migrations.AlterField(
            model_name='canal',
            name='verification_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mensagemsistema',
            name='tipo',
            field=models.CharField(choices=[('info', 'Informação'), ('warning', 'Aviso'), ('error', 'Erro'), ('success', 'Sucesso')], default='info', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='sgp_app',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SGP App'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='sgp_token',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='SGP Token'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='sgp_url',
            field=models.URLField(blank=True, null=True, verbose_name='SGP URL'),
        ),
        migrations.CreateModel(
            name='SystemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Ex: 2.1.5', max_length=20, unique=True)),
                ('version_type', models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('patch', 'Patch')], default='patch', max_length=10)),
                ('title', models.CharField(help_text='Título da versão', max_length=200)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versão do Sistema',
                'verbose_name_plural': 'Versões do Sistema',
                'ordering': ['-release_date', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('feature', 'Nova Funcionalidade'), ('improvement', 'Melhoria'), ('fix', 'Correção'), ('security', 'Segurança')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='core.systemversion')),
            ],
            options={
                'verbose_name': 'Entrada do Changelog',
                'verbose_name_plural': 'Entradas do Changelog',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
