# Generated by Django 5.2.4 on 2025-08-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_label_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OpenAI API Key'),
        ),
    ]
