# Generated by Django 5.2.4 on 2025-08-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_systemconfig_openai_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='key',
            field=models.CharField(blank=True, default='', max_length=255, unique=True, verbose_name='Chave'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='value',
            field=models.TextField(blank=True, default='', verbose_name='Valor'),
        ),
    ]
