# Generated by Django 5.2.4 on 2025-09-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_provedor_documentos_necessarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.JSONField(blank=True, default=list, verbose_name='Permissões Específicas'),
        ),
    ]
