# Generated by Django 5.2.4 on 2025-09-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_conversation_sound',
            field=models.CharField(default='mixkit-digital-quick-tone-2866.wav', max_length=200, verbose_name='Som para Novas Conversas'),
        ),
        migrations.AddField(
            model_name='user',
            name='new_message_sound',
            field=models.CharField(default='mixkit-bell-notification-933.wav', max_length=200, verbose_name='Som para Novas Mensagens'),
        ),
        migrations.AddField(
            model_name='user',
            name='sound_notifications_enabled',
            field=models.BooleanField(default=False, verbose_name='Notificações Sonoras Ativas'),
        ),
    ]
