# Generated by Django 5.2.4 on 2025-09-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_add_session_timeout_to_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canal',
            options={'ordering': ['nome'], 'verbose_name': 'Canal', 'verbose_name_plural': 'Canais'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='provedor',
            options={'ordering': ['nome'], 'verbose_name': 'Provedor', 'verbose_name_plural': 'Provedores'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
