# Generated by Django 5.2.4 on 2025-11-05 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_canal_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemversion',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ChangelogEntry',
        ),
        migrations.DeleteModel(
            name='SystemVersion',
        ),
    ]
