# Generated by Django 5.2.4 on 2025-11-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_systemversion_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='phone_number_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number ID'),
        ),
        migrations.AddField(
            model_name='canal',
            name='status',
            field=models.CharField(default='connected', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='canal',
            name='token',
            field=models.TextField(blank=True, null=True, verbose_name='Access Token'),
        ),
        migrations.AddField(
            model_name='canal',
            name='waba_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='WABA ID'),
        ),
        migrations.AlterField(
            model_name='canal',
            name='tipo',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('whatsapp_session', 'WhatsApp session'), ('whatsapp_oficial', 'WhatsApp Oficial'), ('telegram', 'Telegram'), ('email', 'Email'), ('webchat', 'WebChat'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], default='whatsapp', max_length=50),
        ),
    ]
