# Generated by Django 5.2.4 on 2025-11-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_add_language_to_user'),
    ]

    operations = [
        # REMOVIDO: Campo api_id (já existe no banco)
        
        migrations.AddField(
            model_name='canal',
            name='app_title',
            field=models.CharField(
                blank=True, 
                max_length=200, 
                null=True, 
                verbose_name='App Title'
            ),
        ),
        migrations.AddField(
            model_name='canal',
            name='short_name',
            field=models.CharField(
                blank=True, 
                max_length=100, 
                null=True, 
                verbose_name='Short Name'
            ),
        ),
    ]
