# Generated by Django 5.2.4 on 2025-11-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_add_telegram_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='tipo',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('whatsapp_session', 'WhatsApp QR code'), ('whatsapp_oficial', 'WhatsApp Oficial'), ('telegram', 'Telegram'), ('email', 'Email'), ('webchat', 'WebChat')], default='whatsapp', max_length=50),
        ),
    ]
