# Generated by Django 5.2.4 on 2025-12-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_provedor_redes_sociais_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assignment_message',
        ),
        migrations.AlterField(
            model_name='provedor',
            name='redes_sociais',
            field=models.JSONField(blank=True, help_text='Redes sociais da empresa', null=True),
        ),
    ]
