# Generated by Django 5.2.4 on 2025-11-22 02:28

from django.db import migrations, models
from django.db.migrations.operations.fields import AddField


class AddFieldIfNotExists(AddField):
    """AddField que verifica se a coluna já existe antes de adicionar"""
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        # Verificar se a coluna já existe
        model = to_state.apps.get_model(app_label, self.model_name)
        if schema_editor.connection.vendor == 'sqlite':
            with schema_editor.connection.cursor() as cursor:
                table_name = model._meta.db_table
                cursor.execute(f"PRAGMA table_info({table_name})")
                columns = [row[1] for row in cursor.fetchall()]
                if self.name in columns:
                    # Coluna já existe, não fazer nada
                    return
        
        # Se não existe, executar a operação normal
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_add_whatsapp_oficial_type'),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name='canal',
            name='api_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='API ID'),
        ),
    ]
