# Generated by Django 5.2.4 on 2025-12-02 01:03

from django.db import migrations, models, connection


def remove_openai_add_google(apps, schema_editor):
    """Remove openai_api_key e adiciona google_api_key apenas se necessário"""
    with connection.cursor() as cursor:
        # Verificar quais campos já existem
        if connection.vendor == 'sqlite':
            cursor.execute("PRAGMA table_info(core_systemconfig)")
            existing_columns = {row[1] for row in cursor.fetchall()}
        elif connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='core_systemconfig'
            """)
            existing_columns = {row[0] for row in cursor.fetchall()}
        else:
            existing_columns = set()
        
        # Remover openai_api_key se existir
        # Nota: SQLite não suporta DROP COLUMN diretamente (requer recriar tabela)
        # Por isso, vamos apenas adicionar google_api_key e deixar openai_api_key no SQLite
        # O Django ORM não tentará usar openai_api_key porque o modelo não tem mais esse campo
        if 'openai_api_key' in existing_columns:
            try:
                if connection.vendor == 'postgresql':
                    # PostgreSQL suporta DROP COLUMN
                    cursor.execute("ALTER TABLE core_systemconfig DROP COLUMN openai_api_key")
                # SQLite: não removemos fisicamente, mas o Django não tentará usar o campo
                # pois o modelo não tem mais esse campo definido
            except Exception as e:
                print(f"Erro ao remover openai_api_key: {e}")
        
        # Adicionar google_api_key se não existir
        if 'google_api_key' not in existing_columns:
            try:
                if connection.vendor == 'sqlite':
                    cursor.execute("""
                        ALTER TABLE core_systemconfig 
                        ADD COLUMN google_api_key TEXT
                    """)
                else:
                    cursor.execute("""
                        ALTER TABLE core_systemconfig 
                        ADD COLUMN google_api_key VARCHAR(255)
                    """)
            except Exception as e:
                print(f"Erro ao adicionar google_api_key: {e}")


def reverse_remove_openai_add_google(apps, schema_editor):
    """Reverter: adiciona openai_api_key e remove google_api_key"""
    pass  # Não vamos reverter


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_2_remove_user_assignment_message_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_openai_add_google, reverse_remove_openai_add_google),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='systemconfig',
                    name='openai_api_key',
                ),
                migrations.AddField(
                    model_name='systemconfig',
                    name='google_api_key',
                    field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google API Key'),
                ),
            ]
        ),
    ]
