# Generated by Django
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_provedor_subscription_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='provedor',
            name='subscription_next_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Vencimento'),
        ),
    ]
