# Generated by Django 6.0.2 on 2026-04-14 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_provedor_subscription_next_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilizadores', to='core.provedor', verbose_name='Provedor Associado'),
        ),
        migrations.AlterField(
            model_name='mensagemsistema',
            name='tipo',
            field=models.CharField(choices=[('notificacao', 'Notificação'), ('aviso', 'Aviso'), ('manutencao', 'Manutenção'), ('info', 'Informação'), ('warning', 'Aviso'), ('error', 'Erro'), ('success', 'Sucesso'), ('info', 'Informação')], default='notificacao', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='respostarapida',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='new_conversation_sound',
            field=models.CharField(default='02.mp3', max_length=200, verbose_name='Som para Novas Conversas'),
        ),
        migrations.AlterField(
            model_name='user',
            name='new_message_sound',
            field=models.CharField(default='01.mp3', max_length=200, verbose_name='Som para Novas Mensagens'),
        ),
    ]
